### ISSUE TITLE
Important condition of use.

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [chris1111/Geforce-Kepler-patcher#1]
SecureBootModel Disabled
Please add it to README

**Comment by chris1111** [comment]
Ok thanks

**Comment by chris1111** [comment]
Done

**Comment by albchong** [comment]
I believe csr-active-config=EF0F0000 is an OpenCore configuration that I have not been able to get working with Clover boot loader. Is there a recommendation for Clover?

**Comment by chris1111** [comment]
> I believe csr-active-config=EF0F0000 is an OpenCore configuration that I have not been able to get working with Clover boot loader. Is there a recommendation for Clover?


try **0x867** then verify the status before using the program
csrutil authenticated-root status

**Comment by albchong** [comment]
Thanks Chris, I will try this and report back. :D

**Comment by testhmf33** [comment]
is a big success 
clover 5139 with 0x867 
thank you very much Chris 
![capt1088](https://user-images.githubusercontent.com/91620557/135301756-3f744e5a-a793-4f8d-80c6-26a41999572d.jpeg)
![capt1089](https://user-images.githubusercontent.com/91620557/135301782-22009d88-1972-4419-8c5d-53d860ac19e1.jpeg)

**Comment by albchong** [comment]
@testhmf33, great news. Thanks
