### ISSUE TITLE
not working with nvidia 1650s

### ISSUE THREAD

**Issue by mohammadnt** [chris1111/Geforce-Kepler-patcher#10]
im on mac monterey 12.0.1 21A559 with clover 5142
![Screen Shot 1400-08-30 at 23 53 50](https://user-images.githubusercontent.com/10488361/142778768-ddd4c0f9-11cf-410f-ba1d-bdde2a46b18c.png)

**Comment by chris1111** [comment]
NVIDIA 1650 is Turing architecture
