### ISSUE TITLE
How do i validate my installation?

### ISSUE THREAD

**Issue by cagnulein** [chris1111/Geforce-Kepler-patcher#11]
Hi @chris1111 ,
  i have a proxmox setup with a GeForce GT 710B that worked fine with Big Sur.
Now installed on the same machine Monterey and of course the GPU doesn't work out-of-the-box.
So i found your repository (thanks!) and i try to install it.
All the installation process went well but my card is still not recognized.
Is there any steps that i could do in order to validate the installation of your patch?
Thanks

**Comment by chris1111** [comment]
SecureBootModel must be Disabled in security, you can try to setup a Imac 18.1
Also  csr-active-config ➤ EF0F0000
Make sur Clear NVRAM from opencore tool
That is suppose to be work, its working here without any probleme
![scree366](https://user-images.githubusercontent.com/6248794/142883253-8ca9650d-e04d-4405-ae5b-df35c16101b9.png)

**Comment by cagnulein** [comment]
probably i'm missing something. This is the current status of my installation

<pre>csrutil status csr-active-config
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: disabled
	NVRAM Protections: enabled
	BaseSystem Verification: disabled</pre>

My steps were:
- Gatekeeper disabled and SecureBootModel disabled
- booted on recovery
- csrutil disable
- csrutil authenticated-root disable
- reboot and reset nvram
- installed the patch

I'm doing something wrong for sure but i don't understand what :)

Thanks again for your help!

**Comment by chris1111** [comment]
Not need to disable csrutil authenticated-root disable ​in recovery with OpenCore
[followed this steps](https://github.com/chris1111/Geforce-Kepler-patcher/issues/11#issuecomment-975433258)

**Comment by cagnulein** [comment]
![Schermata 2021-11-24 alle 09 54 41](https://user-images.githubusercontent.com/48216/143206124-1e987109-0e79-47d1-aa04-d646e5556cd8.png)
sorry for the noob question, you mean enter EF0F0000 in the csr-active-config's data field?
Again sorry for the noob question but i feel like an elephant on a glass store right now :D

**Comment by testhmf33** [comment]
yes , it's exactly that 
replace 260F  by  EF0F0000
that's all 
gatekeeper must be deactivate 
REBOOT before patching and reset NVRAM

**Comment by cagnulein** [comment]
It worked! thanks!
