### ISSUE TITLE
Patching with only the GT710

### ISSUE THREAD

**Issue by Chicchi7393** [chris1111/Geforce-Kepler-patcher#13]
Hello, I'm introducing a friend to hackintosh but the problem is that he has an 11th gen I7 processor, so he can't use the integrated graphics. On his old pc, he had a GT710, so today we are doing an OpenCore install with only the GT710 as the graphics card (Big Sur). I found out just now about this patcher but I'm asking myself how can he apply this patch on Monterey, if updating to Monterey would disable his graphics?

**Comment by testhmf33** [comment]
you can update to MONTEREY with the GT 710 
y'll not be full QE/CI !!!
so you need to patch with this patcher 
don't forget before apply the patch !!!!!
csrutil disable
Usage OpenCore csrutil authenticated-root disable (csr-active-config ➤ EF0F0000
Usage Clover csrutil authenticated-root disable (csr-active-config ➤ 0xFEF
This value Also works for Clover (csr-active-config ➤ 0x867
SecureBootModel ➤ Disabled
Gatekeeper must be disable

**Comment by Chicchi7393** [comment]
so you confirm that if he updates (no intergrated graphics card) he can do it? Also, what is qe/ci?

**Comment by testhmf33** [comment]
yes , we can do it [
[[]](https://www.insanelymac.com/forum/topic/24431-what-is-qe-and-ci/)((https://www.insanelymac.com/forum/topic/24431-what-is-qe-and-ci/))
![1200px-We_Can_Do_It!_NARA_535413_-_Restoration_2](https://user-images.githubusercontent.com/91620557/147774796-24d3ecfa-6508-434a-8ee8-39bc83d437b2.jpeg)

**Comment by shoulai** [comment]
version: macOS Monterey 12.1.
Graphics card: gt740.
I executed, csrutil disable and csrutil authenticated-root disable.
Install Geforce-Kepler-patcher
When it is public, it will still prompt that the permission is insufficient. What should I do?

**Comment by chris1111** [comment]
> version: macOS Monterey 12.1. Graphics card: gt740. I executed, csrutil disable and csrutil authenticated-root disable. Install Geforce-Kepler-patcher When it is public, it will still prompt that the permission is insufficient. What should I do?

Monterey its aldeady Public on [Mac AppStore](https://apps.apple.com/us/app/macos-monterey/id1576738294)

**Comment by shoulai** [comment]
![17CFF01E-BB31-4602-9337-6C43329BF705](https://user-images.githubusercontent.com/77687211/149614120-1f55f564-2ec9-46aa-b927-62f0a1cca7b0.png)

executed, csrutil disable and csrutil authenticated-root disable.

**Comment by testhmf33** [comment]
reboot , clear nvram , patch

**Comment by shoulai** [comment]
> reboot , clear nvram , patch

Thank you very much for your help to me.
