### ISSUE TITLE
Can only be connected to 2 monitors

### ISSUE THREAD

**Issue by kcrazy** [chris1111/Geforce-Kepler-patcher#14]
Can only be connected to 2 monitors, the third monitor connected to no use，

Graphics Card：GTX760

**Comment by chris1111** [comment]
This issue is not relate to the GeForce Patcher

**Comment by kcrazy** [comment]
But the previous version 11 is OK

**Comment by chris1111** [comment]
previous Version of macOS

**Comment by kcrazy** [comment]
Yes, previous Version of macOS is OK

**Comment by chris1111** [comment]
So this is no relation of the patcher, patcher not change but macOS yes

**Comment by kcrazy** [comment]
Okay, thank you
