### ISSUE TITLE
CPU caller 2 error Gtx 960

### ISSUE THREAD

**Issue by h3llH0undX** [chris1111/Geforce-Kepler-patcher#16]
Cpu caller 2 error

Boot stuck and cannot continue the boot

Any fix will be appricated i need for development please help me.

**Comment by h3llH0undX** [comment]
I have monterey 12.1 installed

**Comment by testhmf33** [comment]
Maxwell !!!!! not Kepler

**Comment by h3llH0undX** [comment]
> Maxwell !!!!! not Kepler

Can you explain a little please

**Comment by h3llH0undX** [comment]
> 

I didn't get it please help me out Thank you 🙏

**Comment by testhmf33** [comment]
For Hackintosh with Graphics cards based on Kepler architecture only!
for me your graphic card is a Maxwell architecture

**Comment by chris1111** [comment]
The Nvidia GeForce GTX 960  is based on the Maxwell 
Not support  Issue closed
