### ISSUE TITLE
I can NOT use sleep after patch on Monterey 12.1

### ISSUE THREAD

**Issue by ValentinLiu15** [chris1111/Geforce-Kepler-patcher#17]
I can NOT use sleep after patch on Monterey 12.1
Panic log:

` panic(cpu 1 caller 0xffffff7fb6f98256): NVRM[0/1:0:0]: Read Error 0x00070000: CFG 0x0fc610de 0x00100000 0x00000000, BAR0 0xf6000000 0xffffffd057aa1000 0x0e7060a2, D3, P0/3
Panicked task 0xffffff903443b6a0: 11 threads: pid 140: WindowServer
Backtrace (CPU 1), panicked thread: 0xffffff9501c69aa0, Frame : Return Address
0xffffffd07b61ae40 : 0xffffff801d887ddd mach_kernel : _handle_debugger_trap + 0x41d
0xffffffd07b61ae90 : 0xffffff801d9e7d15 mach_kernel : _kdp_i386_trap + 0x145
0xffffffd07b61aed0 : 0xffffff801d9d74e3 mach_kernel : _kernel_trap + 0x533
0xffffffd07b61af20 : 0xffffff801d827a60 mach_kernel : _return_from_trap + 0xe0
0xffffffd07b61af40 : 0xffffff801d8881ad mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffd07b61b060 : 0xffffff801d887966 mach_kernel : _panic_trap_to_debugger + 0x2b6
0xffffffd07b61b0c0 : 0xffffff801e1160b9 mach_kernel : _panic + 0x54
0xffffffd07b61b130 : 0xffffff7fb6f98256 com.apple.nvidia.driver.NVDAResman : _osReadRegistryBinary + 0x470
0xffffffd07b61b1b0 : 0xffffff7fb706506b com.apple.nvidia.driver.NVDAResman : _gpuExecRegOps + 0xd386
0xffffffd07b61b210 : 0xffffff7fb6d9edea com.apple.nvidia.driver.NVDAGK100Hal : __ZN12NVDAGK100HAL5probeEP9IOServicePi + 0x1d880
0xffffffd07b61b260 : 0xffffff7fb6d9ed13 com.apple.nvidia.driver.NVDAGK100Hal : __ZN12NVDAGK100HAL5probeEP9IOServicePi + 0x1d7a9
0xffffffd07b61b2a0 : 0xffffff7fb6f7ed61 com.apple.nvidia.driver.NVDAResman : _rmGenerateSha256Gid + 0x72c5
0xffffffd07b61b340 : 0xffffff7fb707f1d0 com.apple.nvidia.driver.NVDAResman : _vpHalIfacesSetup_VGPUSTUB + 0x51cd
0xffffffd07b61b3a0 : 0xffffff7fb6f67407 com.apple.nvidia.driver.NVDAResman : _nvErrorLog_va + 0x6c2d
0xffffffd07b61b440 : 0xffffff7fb6f5f2c0 com.apple.nvidia.driver.NVDAResman : _rmFreeInternal + 0x12c
0xffffffd07b61b4a0 : 0xffffff7fb6f5f32f com.apple.nvidia.driver.NVDAResman : _rmFreeInternal + 0x19b
0xffffffd07b61b4d0 : 0xffffff7fb6f5cac2 com.apple.nvidia.driver.NVDAResman : _osReadRegistryString + 0x75f
0xffffffd07b61b570 : 0xffffff7fb6f9ca6c com.apple.nvidia.driver.NVDAResman : _insert_registration_func + 0x1308
0xffffffd07b61b6f0 : 0xffffff7fb6f9d4dd com.apple.nvidia.driver.NVDAResman : _NvRmFree + 0x66
0xffffffd07b61b7e0 : 0xffffff7fb676fe40 com.apple.GeForce : __ZN8nvMemory14DestroySurfaceEP16__GLNVsurfaceRec + 0x78
0xffffffd07b61b830 : 0xffffff7fb673d123 com.apple.GeForce : __ZN15nvBaseAllocator24DestroySingleEmptyBufferEP19__GLNVallocatorHeapP28__GLNVallocatorBufferListRech + 0xe7
0xffffffd07b61b860 : 0xffffff7fb673e7d4 com.apple.GeForce : __ZN15nvBaseAllocator4FreeEP21nvAllocatorAllocation + 0x56
0xffffffd07b61b890 : 0xffffff7fb673f3f5 com.apple.GeForce : __ZN11nvAllocator11FreeVirtualEP21nvAllocatorAllocation + 0x2b
0xffffffd07b61b8b0 : 0xffffff7fb67956b5 com.apple.GeForce : __ZN16nvVirtualAddress4freeEv + 0x3d
0xffffffd07b61b8d0 : 0xffffff7fb673450e com.apple.GeForce : __ZN11nvMemoryMap21freeGPUVirtualAddressEv + 0x66
0xffffffd07b61b8f0 : 0xffffff7fb68f4f9e com.apple.iokit.IOAcceleratorFamily2 : __ZNK16IOAccelMemoryMap7releaseEv + 0x8e
0xffffffd07b61b910 : 0xffffff7fb68a40c1 com.apple.iokit.IOAcceleratorFamily2 : __ZN13IOAccelMemory21pruneOrphanedMappingsEv + 0x4b
0xffffffd07b61b940 : 0xffffff7fb68a3f8a com.apple.iokit.IOAcceleratorFamily2 : __ZNK13IOAccelMemory7releaseEv + 0x74
0xffffffd07b61b960 : 0xffffff7fb68c3c2b com.apple.iokit.IOAcceleratorFamily2 : __ZN16IOAccelResource24freeEv + 0x1dd
0xffffffd07b61b990 : 0xffffff7fb68ceb16 com.apple.iokit.IOAcceleratorFamily2 : __ZN24IOAccelSharedUserClient215delete_resourceEj + 0xa2
0xffffffd07b61b9d0 : 0xffffff801e08bd06 mach_kernel : _shim_io_connect_method_scalarI_scalarO + 0x306
0xffffffd07b61ba70 : 0xffffff801e08a3f8 mach_kernel : __ZN12IOUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x278
0xffffffd07b61bac0 : 0xffffff7fb68d02d2 com.apple.iokit.IOAcceleratorFamily2 : __ZN24IOAccelSharedUserClient214externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x80
0xffffffd07b61bb10 : 0xffffff7fb6780373 com.apple.GeForce : __ZN18nvSharedUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0xef
0xffffffd07b61bb60 : 0xffffff801e09462c mach_kernel : _is_io_connect_method + 0x3cc
0xffffffd07b61bcc0 : 0xffffff801d98eca4 mach_kernel : _iokit_server_routine + 0x4e84
0xffffffd07b61bdd0 : 0xffffff801d862e98 mach_kernel : _ipc_kmsg_send + 0x468
0xffffffd07b61be60 : 0xffffff801d8798dd mach_kernel : _mach_msg_overwrite_trap + 0x2bd
0xffffffd07b61bef0 : 0xffffff801d9bad1e mach_kernel : _mach_call_munger64 + 0x22e
0xffffffd07b61bfa0 : 0xffffff801d828246 mach_kernel : _hndl_mach_scall64 + 0x16
      Kernel Extensions in backtrace:
         com.apple.nvidia.driver.NVDAResman(16.0)[879FE28C-BC88-3553-B3C7-1CCFAE357D45]@0xffffff7fb6f2b000->0xffffff7fb71a4fff
            dependency: com.apple.AppleGraphicsDeviceControl(6.4.9)[C44DDD30-1C5B-35EA-99C2-5130D1B59B9A]@0xffffff7fb516a000->0xffffff7fb516dfff
            dependency: com.apple.iokit.IOGraphicsFamily(593)[A327B1FD-1BF3-3D02-A4E5-20A37ED0493E]@0xffffff7fb6a2f000->0xffffff7fb6a5dfff
            dependency: com.apple.iokit.IONDRVSupport(593)[E489AFED-8F7B-39BC-AACE-B315E2665FE8]@0xffffff7fb6a77000->0xffffff7fb6a7ffff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[023CD3FF-4EFC-3455-89C2-FF8BD98013EB]@0xffffff80203d5000->0xffffff80203fffff
         com.apple.iokit.IOAcceleratorFamily2(462.4.1)[73899B24-CF1D-3468-AF75-F6E62058E2A4]@0xffffff7fb68a2000->0xffffff7fb690bfff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[11A5AE25-9819-386C-ABF0-088AA250EC30]@0xffffff801ef6c000->0xffffff801ef8dfff
            dependency: com.apple.iokit.IOGraphicsFamily(593)[A327B1FD-1BF3-3D02-A4E5-20A37ED0493E]@0xffffff7fb6a2f000->0xffffff7fb6a5dfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[023CD3FF-4EFC-3455-89C2-FF8BD98013EB]@0xffffff80203d5000->0xffffff80203fffff
            dependency: com.apple.iokit.IOReportFamily(47)[097D0056-1E44-3A97-8AD8-8D0F6B76113E]@0xffffff8020411000->0xffffff8020413fff
            dependency: com.apple.iokit.IOSurface(302.9)[8F577265-9368-32C8-B7AE-071532EE9337]@0xffffff8020544000->0xffffff8020560fff
         com.apple.GeForce(16.0)[B907167E-E164-36D8-9E8F-695A72E738F7]@0xffffff7fb672d000->0xffffff7fb67a7fff
            dependency: com.apple.iokit.IOAcceleratorFamily2(462.4.1)[73899B24-CF1D-3468-AF75-F6E62058E2A4]@0xffffff7fb68a2000->0xffffff7fb690bfff
            dependency: com.apple.iokit.IOGraphicsFamily(593)[A327B1FD-1BF3-3D02-A4E5-20A37ED0493E]@0xffffff7fb6a2f000->0xffffff7fb6a5dfff
            dependency: com.apple.iokit.IONDRVSupport(593)[E489AFED-8F7B-39BC-AACE-B315E2665FE8]@0xffffff7fb6a77000->0xffffff7fb6a7ffff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[023CD3FF-4EFC-3455-89C2-FF8BD98013EB]@0xffffff80203d5000->0xffffff80203fffff
            dependency: com.apple.iokit.IOSurface(302.9)[8F577265-9368-32C8-B7AE-071532EE9337]@0xffffff8020544000->0xffffff8020560fff
            dependency: com.apple.nvidia.driver.NVDAResman(16.0.0)[879FE28C-BC88-3553-B3C7-1CCFAE357D45]@0xffffff7fb6f2b000->0xffffff7fb71a4fff
         com.apple.nvidia.driver.NVDAGK100Hal(16.0)[CCDFB15A-E29E-38CE-A6C0-732F5648BC28]@0xffffff7fb6d80000->0xffffff7fb6ea2fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[023CD3FF-4EFC-3455-89C2-FF8BD98013EB]@0xffffff80203d5000->0xffffff80203fffff
            dependency: com.apple.nvidia.driver.NVDAResman(16.0.0)[879FE28C-BC88-3553-B3C7-1CCFAE357D45]@0xffffff7fb6f2b000->0xffffff7fb71a4fff

Process name corresponding to current thread (0xffffff9501c69aa0): WindowServer
Boot args: keepsyms=1 alcid=5 nvda_drv_vrl=1 -lilubetaall vsmcgen=1

Mac OS version:
21C52

Kernel version:
Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
Kernel UUID: E32C293C-7D8B-327C-A335-6AAD250A4881
KernelCache slide: 0x000000001d600000
KernelCache base:  0xffffff801d800000
Kernel slide:      0x000000001d610000
Kernel text base:  0xffffff801d810000
__HIB  text base: 0xffffff801d700000
System model name: MacPro6,1 (Mac-F60DEB81FF30ACF6)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 4760695172624
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000004546f8b714a
  Sleep   : 0x000004546193b614 0x00000013e569b046 0x0000000000000000
  Wake    : 0x000004546ed74d9d 0x00000000c442c5e4 0x000004546e069511
Zone info:
Foreign   : 0xffffff8027e0b000 - 0xffffff8027e18000
Native    : 0xffffff803436a000 - 0xffffffa03436a000
Readonly  : 0xffffff8501036000 - 0xffffff869a9ca000
Metadata  : 0xffffffdc3a056000 - 0xffffffdc5a11c000
Bitmaps   : 0xffffffdc5a11c000 - 0xffffffdc

`

**Comment by testhmf33** [comment]
your boot args contain :nvda_drv_vrl=1
don't work in MONTEREY 
SINCE HIGH SIERRA Web drivers are not compatible 
this patcher is for graphic card KEPLER 
what is your Graphic Card ????
![Capture d’écran 2022-01-27 à 15 19 39](https://user-images.githubusercontent.com/91620557/151377102-7cf519b3-fbdf-4bcb-9aa0-a5a8a9cc9b83.png)
?

**Comment by ValentinLiu15** [comment]
> your boot args contain :nvda_drv_vrl=1
> don't work in MONTEREY
> SINCE HIGH SIERRA Web drivers are not compatible
> this patcher is for graphic card KEPLER
> what is your Graphic Card ????
> ![Capture d’écran 2022-01-27 à 15 19 39](https://user-images.githubusercontent.com/91620557/151377102-7cf519b3-fbdf-4bcb-9aa0-a5a8a9cc9b83.png)
> ?

my graphic card is GTX650 (GK107) patched for UEFI and I will remove this boot arg next time.

**Comment by ValentinLiu15** [comment]
@testhmf33 This is a new panic log after remove 'nvda_drv_vrl=1' boot arg:
`panic(cpu 0 caller 0xffffff800ea3ebf1): AppleHDAHDMI_DPDriver::setPowerState(0xffffff868b83e300 : 0xffffff7fa5c11070, 0 -> 1) timed out after 10169 ms @IOServicePM.cpp:5524
Panicked task 0xffffff868b40f670: 176 threads: pid 0: kernel_task
Backtrace (CPU 0), panicked thread: 0xffffff90253aeaa0, Frame : Return Address
0xffffffd07a62bab0 : 0xffffff800e287ddd mach_kernel : _handle_debugger_trap + 0x41d
0xffffffd07a62bb00 : 0xffffff800e3e7d15 mach_kernel : _kdp_i386_trap + 0x145
0xffffffd07a62bb40 : 0xffffff800e3d74e3 mach_kernel : _kernel_trap + 0x533
0xffffffd07a62bb90 : 0xffffff800e227a60 mach_kernel : _return_from_trap + 0xe0
0xffffffd07a62bbb0 : 0xffffff800e2881ad mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffd07a62bcd0 : 0xffffff800e287966 mach_kernel : _panic_trap_to_debugger + 0x2b6
0xffffffd07a62bd30 : 0xffffff800eb160b9 mach_kernel : _panic + 0x54
0xffffffd07a62bda0 : 0xffffff800ea3ebf1 mach_kernel : __ZN9IOService12ackTimerTickEv + 0x801
0xffffffd07a62be00 : 0xffffff800ea3e3b9 mach_kernel : __ZN9IOService21actionAckTimerExpiredEP8OSObjectPvS2_S2_S2_ + 0x9
0xffffffd07a62be10 : 0xffffff800ea5740e mach_kernel : __ZN10IOWorkLoop9runActionEPFiP8OSObjectPvS2_S2_S2_ES1_S2_S2_S2_S2_ + 0x3e
0xffffffd07a62be50 : 0xffffff800ea3d148 mach_kernel : __ZN9IOService17ack_timer_expiredEPvS0_ + 0x38
0xffffffd07a62be70 : 0xffffff800e2db015 mach_kernel : _thread_call_delayed_timer + 0x4f5
0xffffffd07a62bee0 : 0xffffff800e2dc082 mach_kernel : _thread_call_delayed_timer + 0x1562
0xffffffd07a62bfa0 : 0xffffff800e22718e mach_kernel : _call_continuation + 0x2e

Process name corresponding to current thread (0xffffff90253aeaa0): kernel_task
Boot args: keepsyms=1 alcid=5 -lilubetaall vsmcgen=1

Mac OS version:
21C52

Kernel version:
Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
Kernel UUID: E32C293C-7D8B-327C-A335-6AAD250A4881
KernelCache slide: 0x000000000e000000
KernelCache base:  0xffffff800e200000
Kernel slide:      0x000000000e010000
Kernel text base:  0xffffff800e210000
__HIB  text base: 0xffffff800e100000
System model name: MacPro6,1 (Mac-F60DEB81FF30ACF6)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 1014585559069
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000000ec3a030b6e
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000017134b7dc8 0x0000000000000000
Zone info:
Foreign   : 0xffffff801880b000 - 0xffffff8018818000
Native    : 0xffffff8024bf3000 - 0xffffffa024bf3000
Readonly  : 0xffffff84f18bf000 - 0xffffff868b253000
Metadata  : 0xffffffdd00a73000 - 0xffffffdd20b37000
Bitmaps   : 0xffffffdd20b37000 - 0xffffffdd23b37000
last started kext at 255489354261: @filesystems.exfat	1.4 (addr 0xffffff7fa7dad000, size 53248)
last stopped kext at 156953315208: @nvidia.NVDAStartup	16.0.0 (addr 0xffffff7fa7be2000, size 8192)
loaded kexts:
com.insanelymac.RealtekRTL8111	2.4.2
ru.joedm.SMCSuperIO	1.2.8
as.vit9696.SMCProcessor	1.2.8
as.vit9696.VirtualSMC	1.2.8
as.lvs1974.HibernationFixup	1.4.5
as.vit9696.WhateverGreen	1.5.6
com.rehabman.driver.USBInjectAll	0.7.8
as.vit9696.!AALC	1.6.8
as.acidanthera.BlueToolFixup	2.6.1
as.vit9696.Lilu	1.5.9
org.tgwbd.driver.NullCPUPowerManagement	1.0.0d2
@filesystems.exfat	1.4
@filesystems.msdosfs	1.10
>AudioAUUC	1.70
@filesystems.autofs	3.0
@fileutil	20.036.15
>AGPM	127
>X86PlatformShim	1.0.0
>!APlatformEnabler	2.7.0d0
>!AHDA	283.15
@AGDCPluginDisplayMetrics	6.4.9
>pmtelemetry	1
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
>!AHV	1
>!ADiskImages2	126.60.3
>!A!IPCHPMC	2.0.1
@GeForce	16.0.0
>!AUpstreamUserClient	3.6.8
>!AMCCSControl	1.14
>!A!IMCEReporter	115
>!A!ISlowAdaptiveClocking	4.0.0
@filesystems.apfs	1933.61.1
@private.KextAudit	1.0
|SCSITaskUserClient	452.60.2
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.lifs	1
@filesystems.hfs.kext	582.60.2
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
>!AAHCIPort	351
>!ARTC	2.0.1
>!AACPIButtons	6.1
>!AHPET	1.8
>!ASMBIOS	2.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	402
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
@Dont_Steal_Mac_OS_X	7.0.0
>!A!ICPUPowerManagement	222.0.0
@kec.!AEncryptedArchive	1
>driverkit.serial	6.0.0
|IOSerial!F	11
@kext.triggers	1.0
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
|IO!BSerialManager	9.0.0
|IO!BPacketLogger	9.0.0
|IO!BHost!CUSBTransport	9.0.0
|IO!BHost!CUARTTransport	9.0.0
|IO!BHost!CTransport	9.0.0
>IO!BHost!CPCIeTransport	9.0.0
|IOAVB!F	1010.2
@plugin.IOgPTPPlugin	1000.11
|IOEthernetAVB!C	1.1.0
|CSR!BHost!CUSBTransport	9.0.0
|Broadcom!BHost!CUSBTransport	9.0.0
|Broadcom!B20703USBTransport	9.0.0
>!AIPAppender	1.0
|IOSkywalk!F	1.0
>mDNSOffloadUserClient	1.0.1b8
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
>!UAudio	413.5
>!AAudioClockLibs	100.9.1
>!AHDA!C	283.15
|IOHDA!F	283.15
|IOAudio!F	300.10
@vecLib.kext	1.2.0
|IOAccelerator!F2	462.4.1
@nvidia.driver.NVDAGK100Hal	16.0.0
@nvidia.driver.NVDAResman	16.0.0
>!ASMBus!C	1.0.18d1
|IOSMBus!F	1.1
|IONDRVSupport	593
@!AGPUWrangler	6.4.9
@!AGraphicsDeviceControl	6.4.9
|IOGraphics!F	593
|IOSlowAdaptiveClocking!F	1.0.0
>!AXsanScheme	3
|IOAHCIBlock!S	333
>usb.IOUSBHostHIDDevice	1.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!ABSDKextStarter	3
|IOSurface	302.9
@filesystems.hfs.encodings.kext	1
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
|IOAHCI!F	295
>!A!ILpssGspi	3.0.60
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
|IOTimeSync!F	1000.11
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	9.0.0
|IOReport!F	47
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	532.40.7
|IOUSBMass!SDriver	209.40.6
|IOSCSIBlockCommandsDevice	452.60.2
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	452.60.2
>!AMobileFileIntegrity	1.0.5
$!AImage4	4.2.0
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.Libm	1
@kec.corecrypto	12.0


`

**Comment by chris1111** [comment]
Reset NVRAM

**Comment by ValentinLiu15** [comment]
Success by reset NVRAM！
