### ISSUE TITLE
No Signal

### ISSUE THREAD

**Issue by Jbmanid** [chris1111/Geforce-Kepler-patcher#20]
Apply GT710 2GB. After Patch using nv_disable=1, detected : Nvidia Chip Model 7MB. When erase nv_disable=1, no signal. So, only work with nv_disable =1. What is the solution?

**Comment by Jbmanid** [comment]
> Apply GT710 2GB. After Patch using nv_disable=1, detected : Nvidia Chip Model 7MB. When erase nv_disable=1, no signal. So, only work with nv_disable =1. What is the solution?

Work perfectly for me add at boot-args with value nv_drv=1, Well Done !

**Comment by chris1111** [comment]
nv_drv=1 its a boot arg for web Drivers
