### ISSUE TITLE
SecureBootModel select Default can only enter recovery mode

### ISSUE THREAD

**Issue by ghost** [chris1111/Geforce-Kepler-patcher#21]
How to solve the problem that the version update cannot be automatically obtained after SecureBootModel is disabled?

**Comment by chris1111** [comment]
I have SecureBootModel disabled without any issue to obtained update
dont know whats wrong in your config setup?

EDIT***

**Comment by ghost** [comment]
<img width="663" alt="截屏2022-03-05 12 43 22" src="https://user-images.githubusercontent.com/12277040/156868239-06fb0f64-6812-4f03-b376-b27c3cfcbf48.png">

**Comment by chris1111** [comment]
Its a Apple Beta Software

Use Developer Beta to have Update
[Monterey-Beta-Software-Utility](https://github.com/chris1111/Monterey-Beta-Software-Utility)

**Comment by benladengtd** [comment]
Thank you very much

**Comment by ghost** [comment]
> 它是一个 Apple Beta 软件
> 
> 使用 Developer Beta 更新 [Monterey-Beta-Software-Utility](https://github.com/chris1111/Monterey-Beta-Software-Utility)
Thank you very much
