### ISSUE TITLE
Weird graphics artifacts on Memoji 

### ISSUE THREAD

**Issue by alexmarleron** [chris1111/Geforce-Kepler-patcher#22]
gt710 and gt 640 Monterey 12.1-12.2.1
![123](https://user-images.githubusercontent.com/77567689/158653935-ca906b7e-4ea7-4f8b-a64e-d1688db08d20.png)

**Comment by chris1111** [comment]
its time to update monterey man because this issue is gone
![Screen Shot 2022-03-16 at 3 35 16 PM](https://user-images.githubusercontent.com/6248794/158675722-f1e21145-ec62-4646-a7d5-d407f8ef5a2c.png)

**Comment by alexmarleron** [comment]
12.3 Same problem Kepler patcher v1 and v2
![456](https://user-images.githubusercontent.com/77567689/158745437-822fe79f-b4ee-4236-9c53-2405ffa81ea5.png)

**Comment by chris1111** [comment]
Patcher works without issue GT 710

**Comment by chris1111** [comment]
EDIT I am using Clover 😄

**Comment by macenjoyer** [comment]
Still here, but it was present for me on Big Sur too, so doesn't look like a patcher issue.

![Screenshot 2022-04-10 at 16 58 10](https://user-images.githubusercontent.com/103370823/162623029-99669119-a8e5-45d3-a673-9a127a76246e.png)
