### ISSUE TITLE
6600xt

### ISSUE THREAD

**Issue by rclsmart** [chris1111/Geforce-Kepler-patcher#24]
Currently, the MSI mortar cannot be installed with the 12 system, and can only drive 11.6 6600xt

**Comment by rclsmart** [comment]
Can not drive the 6600xt on the 11.6, because the mortar B550 cannot be installed on the 12 system

**Comment by chris1111** [comment]
6600xt is a AMD graphics card , nothing to do with GeForce kepler patcher
MSI mortar is a Motherboard nothing to do with GeForce kepler patcher
