### ISSUE TITLE
i5-9400F GT710 Panic after patch

### ISSUE THREAD

**Issue by AK-3696** [chris1111/Geforce-Kepler-patcher#26]
I have done all the steps mentioned like csrutil disable and gatekeeper disable and applied the patch. I get bad encryption key and end up in a panic saying disk is not readable.

Monterey Version 12.3.1
Gigabyte H310M board
i5-9400F
16 GB Ram
Gigabyte GT 710 2GB

**Comment by AK-3696** [comment]
[https://i.imgur.com/jb1DCgH.png](url)
[https://i.imgur.com/w8Cij0G.png](url)
[https://i.imgur.com/4dYt3Ag.png](url)
[https://i.imgur.com/5wa1GwF.png](url)

**Comment by chris1111** [comment]
Its csrutil authenticated-root disable

**Comment by AK-3696** [comment]
> Its csrutil authenticated-root disable

Yes i have disabled as said in guide by changing the csr_active_config value

**Comment by chris1111** [comment]
Did you Reset NVRAM? after changing this value

**Comment by AK-3696** [comment]
Can you please tell whether the steps below are right? Tell me where I'm wrong

1. sudo spctl --master-disable
2. Boot to recovery
3. Open terminal
4. csrutil disable
5. csrutil authenticate-root disable
6. reboot
7. Apply Patch
8. select monterey-DISK
9. Reboot
10. Ended up in panic

**Comment by chris1111** [comment]
[Here](https://github.com/chris1111/Geforce-Kepler-patcher#important-note-the-csrutil-authenticated-root-values-must-be-applied-before-you-use-this-peogram-so-if-you-have-not-already-changed-and-made-a-reset-nvram-do-it-and-reboot-then-use-the-program-also-securebootmodel-must-be-disabled-in-configplist)

**Comment by chris1111** [comment]
Reset NVRAM from Bootloader thats it

**Comment by AK-3696** [comment]
Done all the steps mentioned and also reset NV RAM done. But still ended up in panic. Is there a way to reboot from snapshot disk?

**Comment by AK-3696** [comment]
Yeah i have managed to install somehow. Thanks for your help. One more doubt here. After installing, it can detect GT710 2GB. Now can i re-enable SIP and gatekeeper?

**Comment by AK-3696** [comment]
Thanks it is resolved after doing all the steps. Please tell whether can i enable SIP or not?

**Comment by chris1111** [comment]
No Sip must be disable

**Comment by chris1111** [comment]
You can try **00080000**  
Reset Nvram after change the value
