### ISSUE TITLE
Xcode Glitch

### ISSUE THREAD

**Issue by alexmarleron** [chris1111/Geforce-Kepler-patcher#27]
I've got this glitch when working as visual edit in the storyboard and simulator is blank when preview project (Xcode 13.3) but in Xcode 13.2 all works fine
gt710 OpenCore 0.7.9 Geforce-Kepler-patcher-V2
 ![Screen Shot 2022-04-12 at 08 56 57 (2)](https://user-images.githubusercontent.com/77567689/162895114-2d57bc77-a724-4d96-a683-50741e5ac63c.png)

**Comment by chris1111** [comment]
I'm not surprised, don't expect perfection with such a patch
