### ISSUE TITLE
Error: 75 @ 60%

### ISSUE THREAD

**Issue by wdluya** [chris1111/Geforce-Kepler-patcher#28]
When trying to install the Kepler driver using patcher-2, at around 60% a popup appears asking for my password, but after giving the password, it shows an error:

Error: 75. mount_apfs: volume could not be mounted: Resource busy
mount: /System/Volumes/Update/mnt1 failed with 75
I did disable secure boot loader, csrutil and gatekeeper conform instructions.

**Comment by chris1111** [comment]
Reboot retry please

**Comment by wdluya** [comment]
Thank you for your reply!  I have retryed multiple times, but still show the same error。I have installed a patcher-1 before, and an error will be reported when I install patcher-2 again。

**Comment by wdluya** [comment]
> Reboot retry please

Thank you for your reply! I have retryed multiple times, but still show the same error。I have installed a patcher-1 before, and an error will be reported when I install patcher-2 again。

**Comment by chris1111** [comment]
Before runing the patcher type this in terminal following by Enter

`diskutil unmount /System/Volumes/Update/mnt1`

**Comment by ghost** [comment]
> 

returning an error, cant unmnount this
