### ISSUE TITLE
Breaks OpenCore

### ISSUE THREAD

**Issue by RiDDiX** [chris1111/Geforce-Kepler-patcher#3]
Maybe it is a fault at my side, but when I use your patcher as mentioned and reboot my system I get error messeges about bad encryptionkeys and cant mount apfs. 

I really dont know why, but when your patcher set up the new snapshot partition it breaks my whole system...

I cant even get the error reports...

**Comment by chris1111** [comment]
Strange? because I use it without any error after an update and it puts everything back in place after the reboot.
Difficult to know what is your problem without any Log or boot image, What is the OC version and which macOS Monterey Beta version you are using? could you send your config.plist in ZIP here and File Vault is not activated I hope

**Comment by RiDDiX** [comment]
Monterey Beta 8 and 9. OpenCore Version 0.7.5

BigSur runs without any problem. Yes of course because the nvidia drivers are still in, but yeah
[config.plist.zip](https://github.com/chris1111/Geforce-Kepler-patcher/files/7353186/config.plist.zip)
. 

I removed my Platforminformations... Hope this is ok. Mac Pro (2019)

If I update to Monterey Beta 8 or 9 or 10 and apply the patcher (followed as mentioned in your github disable gatekeeper secure boot and so on). And restart after patching it just breaks. (Error apfs volume disk1s* cant be mounted and or encryptionkeys update error)

**Comment by RiDDiX** [comment]
Never mind. Found my problem. Got irritated with the "select apfs monterey-disk" maybe I selected the wrong one. After fresh install big sur and updated to Monterey Beta 10 then applied settings and "patched" it, everything now works. 

Sorry for the hassle / trouble!
