### ISSUE TITLE
Cannot apply patch due to error 77

### ISSUE THREAD

**Issue by dpenra** [chris1111/Geforce-Kepler-patcher#30]
After entering pass code during kepler patch error shows. I research all but could not find any solution
Motherboard=msi tomahwak max
Cpu ryzen 5 3600
Gpu=nvidia gt 710 2gdb
Macos=monterey
Please look for the image for further info
![IMG_20220503_184217](https://user-images.githubusercontent.com/36838592/166480644-b9aea9b4-1d60-43a1-8900-812b93990c8f.jpg)

**Comment by chris1111** [comment]
This issue appears if csrutil authenticated-root disable was not well done

**Comment by dpenra** [comment]
thank you. i forgot to reset nvram. which is also a crucial part.......
