### ISSUE TITLE
k3100m (not an issue)

### ISSUE THREAD

**Issue by originalshop019** [chris1111/Geforce-Kepler-patcher#31]
## This is not an issue but i couldn't find  where to start this discussion ##

So, i've nvidia k3100m which is a kepler...i was wondering if this patch works with this dgpu?

**Comment by chris1111** [comment]
This GPU is based on the Kepler architecture
So yes it should work

**Comment by originalshop019** [comment]
Thank u man, and i love ur work, god bless u

**Comment by originalshop019** [comment]
So, i used the patch and my hack is broken, stuck on boot loop then it goes to recovery

**Comment by testhmf33** [comment]
have you configured like that ????  
Usage OpenCore: csrutil authenticated-root disable csr-active-config ➤ EF0F0000
Usage Clover: csrutil authenticated-root disable csr-active-config ➤ 0xFEF

**Comment by originalshop019** [comment]
> have you configured like that ????  
> Usage OpenCore: csrutil authenticated-root disable csr-active-config ➤ EF0F0000
> Usage Clover: csrutil authenticated-root disable csr-active-config ➤ 0xFEF

Yes i disabled the sip
for the "csrutil authenticated-root disable", i'm not sure if i did it the right way
So, now i'm reinstalling the whole hack, when i finish i'll repatch and double check for these configs

**Comment by testhmf33** [comment]
before patching 
reboot and reset your nvram

**Comment by originalshop019** [comment]
ok, so what i'll do:

1. Disable Configs recommanded by the patcher
2. Reboot 
3. Reset nVram from OC
4. Patch...

i hope that will work !!!!

**Comment by testhmf33** [comment]
it's the good way 
don't forget to disable gatekeeper

**Comment by chris1111** [comment]
If you are using a laptops for making hackintosh the patch in is not responsable of the config you are trying 
EDIT *** 
I hope for you this Hackintosh is already build on a macOS compatible version

**Comment by originalshop019** [comment]
I'm using monterey 12.3.1
My specs: 
zbook g2 17 workstation
I5 4330m (vPro)
Igpu : hd4600
16Gb ddr3
dgpu: k3100m

Everything is working:
wifi, bluetooth, sound, ethernet, usb

Not working: video acceleration (gpu not recognized)
I used these configs
ig-platform: 0600260A
device-id: 12040000
framebuffer-patch-enable: 01000000
framebuffer-cursormem: 00009000


![IMG_20220504_225223.jpg](https://user-images.githubusercontent.com/63241839/167026764-b99e0d86-a7b8-4dc2-bf8d-60611f394a51.jpg)

May be i will use only igpu

**Comment by originalshop019** [comment]
> it's the good way 
> don't forget to disable gatekeeper 

csrutil status => uknown
csrutil Authenticate-root: disable
gatekeeper => disabled

in config.plist => csr-active is EF0F0000
nvram resetted

So, Could i patch now?

**Comment by chris1111** [comment]
This programm is not to help people to build Hackintosh! You need to build your hackintosh laptop yourself but I suggest to you to build this on macOS compatible like Big sur 11 you have to go to hackintosh forums to do this
