### ISSUE TITLE
Error installing (quadro k1100m)

### ISSUE THREAD

**Issue by avelarfe** [chris1111/Geforce-Kepler-patcher#32]
I'm getting this issue. Everything is done (SIP, opencore entry, gatekeeper off)...

![Captura de Tela 2022-05-12 às 19 55 33](https://user-images.githubusercontent.com/21061728/168180481-5a79eace-6fe8-4b88-b751-ac4fab23ae51.png)

**Comment by chris1111** [comment]
https://github.com/chris1111/Geforce-Kepler-patcher#troubleshooting-terminal--tccutil-reset-appleevents

**Comment by ghost** [comment]
@chris1111 I get this issue too. But only with V3. Version 2 works with the same settings.
