### ISSUE TITLE
Geforce GT710 2GB not working

### ISSUE THREAD

**Issue by tele81** [chris1111/Geforce-Kepler-patcher#33]
hello i have installed the current monterey oc 0.8.

The Geforce GT710 2GB is not recognized.

SIP everything out as in the instructions.

Kepler Patcher v2 puts me in recovery mode.

Kepler Patcher v3 won't run, Unable to pass Error Patcher Script to Finder.

OC Legancy Patcher also gets me into recovery mode.

As written, everything is switched off, including the gatekeeper.

Any idea?

**Comment by chris1111** [comment]
https://github.com/chris1111/Geforce-Kepler-patcher/issues/32
