### ISSUE TITLE
kepler patch installed but unsuccessfull

### ISSUE THREAD

**Issue by dpenra** [chris1111/Geforce-Kepler-patcher#34]
![Screen Shot 2022-05-18 at 10 51 59](https://user-images.githubusercontent.com/36838592/169011681-cee0086e-4abc-4510-861f-37c2d95fbafe.png)
![Screen Shot 2022-05-18 at 10 38 49](https://user-images.githubusercontent.com/36838592/169011712-1e475433-3660-40ef-a5c2-f88488d2e4a9.png)
i have successfully installed kepler patch but there was no effect. as you can see in pic

**Comment by testhmf33** [comment]
what is the  graphics card exactly ????

**Comment by mayur43s** [comment]
@dpenra Try version 2 instead of 3. Version 3 was not working for me for GT 710 but version 2 did work like a charm.

**Comment by dpenra** [comment]
its gt 710 gt

**Comment by dpenra** [comment]
> what is the graphics card exactly ????

nvidia gt 710

**Comment by dpenra** [comment]
> @dpenra Try version 2 instead of 3. Version 3 was not working for me for GT 710 but version 2 did work like a charm.

can we again re-apply the patch on the same disk?

**Comment by chris1111** [comment]
> > @dpenra Try version 2 instead of 3. Version 3 was not working for me for GT 710 but version 2 did work like a charm.
> 
> can we again re-apply the patch on the same disk?


All version work here GT 710

**Comment by dpenra** [comment]
> > > @dpenra Try version 2 instead of 3. Version 3 was not working for me for GT 710 but version 2 did work like a charm.
> > 
> > 
> > can we again re-apply the patch on the same disk?
> 
> All version work here GT 710

will kepler patch work on 12.4

**Comment by testhmf33** [comment]
of course and 12.5 bèta 1 tested 
patcher V3 without any problem on two PC 
![Capture d’écran 2022-05-19 à 09 56 01](https://user-images.githubusercontent.com/91620557/169259472-748c5884-27bf-435d-ac9e-3ea50d53388c.png)
![Capture d’écran 2022-05-19 à 10 38 11](https://user-images.githubusercontent.com/91620557/169259482-7413365a-15dc-414d-b061-1c6596a51364.png)

**Comment by chris1111** [comment]
> of course and 12.5 bèta 1 tested patcher V3 without any problem on two PC ![Capture d’écran 2022-05-19 à 09 56 01](https://user-images.githubusercontent.com/91620557/169259472-748c5884-27bf-435d-ac9e-3ea50d53388c.png) ![Capture d’écran 2022-05-19 à 10 38 11](https://user-images.githubusercontent.com/91620557/169259482-7413365a-15dc-414d-b061-1c6596a51364.png)

Thanks I know the V3  work the same, some people dont follow the guide

**Comment by mayur43s** [comment]
@chris1111 Thanks much for this patcher but I've followed the guide and V3 didn't work so I've moved to V2. I've tried it on macOS 12.2.1 and not a beta version.

**Comment by chris1111** [comment]
Stop to say anything
![Screen Shot 2022-05-19 at 3 35 11 PM](https://user-images.githubusercontent.com/6248794/169389316-175ff3ff-7aab-4d84-b923-0d479eef6d12.png)

![Screen Shot 2022-05-19 at 3 36 25 PM](https://user-images.githubusercontent.com/6248794/169389342-b39a9a9a-7290-4e40-baf7-1d2ed0f905c9.png)


![Screen Shot 2022-05-19 at 3 38 33 PM](https://user-images.githubusercontent.com/6248794/169389366-16f91765-a0cc-4eef-aca5-4b1e89d5cc0d.png)
