### ISSUE TITLE
Runtime script error (solved)

### ISSUE THREAD

**Issue by lwabish** [chris1111/Geforce-Kepler-patcher#35]
after starting the app and select my disk the first time,
error occured:
not authorized to send apple events to finder
mac os 12.4

**Comment by chris1111** [comment]
https://github.com/chris1111/Geforce-Kepler-patcher#troubleshooting-terminal--tccutil-reset-appleevents
Terminal
`tccutil reset AppleEvents`
Reboot 
Try latest release 
[Latest Release](https://github.com/chris1111/Geforce-Kepler-patcher/releases/tag/V3)

**Comment by lwabish** [comment]
Problem solved, thanks a lot
