### ISSUE TITLE
Can i revert back all setting to default after sucessfully installation of this patch?

### ISSUE THREAD

**Issue by dpenra** [chris1111/Geforce-Kepler-patcher#36]
Is there any abnormality to the system if I change the setting back to default after patching?
like
csrutil enable, csrutil authenticated-root enable, csr-active-config ➤ 00000000, SecureBootModel ➤ Default

**Comment by chris1111** [comment]
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/post-issues.html#disabling-sip
