### ISSUE TITLE
Display goes off after booting

### ISSUE THREAD

**Issue by sharad-paghadal** [chris1111/Geforce-Kepler-patcher#37]
After applying patch, system starts normally in booting logs, but at the end display just goes off. Anything I can try?

**Comment by sharad-paghadal** [comment]
My config:
Lenovo M93p
- i5 4th Gen
- 710 2GB graphics
- Used iMac17,1

**Comment by chris1111** [comment]
try HDMI instead of DVI

**Comment by sharad-paghadal** [comment]
I'm using HDMI only

**Comment by zerrjay31** [comment]
not appearing my gtx 1060 in monterey

**Comment by zerrjay31** [comment]
my spec i5 9600k using gtx 1060

**Comment by testhmf33** [comment]
this patch is for kepler card only 
for your gtx 1060 you need web driver

**Comment by sharad-paghadal** [comment]
@chris1111 
I've tried setting Motherboard setting to use integrated graphics and it booted with built in DP port (Not from Graphics Card).

Meaning, after applying the patch, it's somehow not able to transmit display to graphics HDMI port.

**Comment by chris1111** [comment]
If is booted from Intergrate Graphics you have seting up DeviceProperties in config.plist this is probably the issue here

**Comment by sharad-paghadal** [comment]
@chris1111 
Issue fixed by changing configuration to iMac18,3
