### ISSUE TITLE
macOS Ventura no driver successful for GTX770

### ISSUE THREAD

**Issue by zxfgll** [chris1111/Geforce-Kepler-patcher#39]
Hello, macOS Ventura uses your Geforce-Kepler-patcher software, the driver file is added to system/library/extensions, no driver is successful, but It can be used successfully on mac12.3.1

**Comment by apsinghnandha** [comment]
Same issue with GT730 on macOS13 dev beta

**Comment by shigure1107** [comment]
Same issue with GTX670 on macOS13

**Comment by chris1111** [comment]
https://github.com/chris1111/Geforce-Kepler-patcher/issues/40
