### ISSUE TITLE
Patch bricks system after applying (Monterey Release 12.0.1)

### ISSUE THREAD

**Issue by AO554** [chris1111/Geforce-Kepler-patcher#4]
After installing the day-one release of Monterey and applying the patch, OpenCore tries to hand-off to the Kernel but instantly reboots after that.

I tried reinstalling Monterey, I got back in, reapplied the patch making sure it was Monterey-DISK, to the same issue again

**Comment by AO554** [comment]
Furthermore to add, after finding out it didn't like something to do with OpenCore's Default Secure Boot model, changing that to disabled got us to boot the Kernel, but only so far as it eventually lead into a Kernel Panic

**Comment by chris1111** [comment]
Strange I just install release 12.0.1 (21A559) on my Optiplex sandy Bridge + Geforce 710 without any issue
![Screen Shot 2021-10-21 at 9 18 30 PM](https://user-images.githubusercontent.com/6248794/138844873-edc71cb6-d4f2-4167-916c-50c441535f15.png)

**Comment by AO554** [comment]
Strange, its every time I install the patch for my GT 740, it goes through the normal steps of renaming my boot drive, asks me to select it and then applies and Tells me to reboot. but whenever I'm trying to boot the patched disk, it just halts here

panic(cpu 4 caller 0xffffff800afcb394): System KC UUID 6A589D20-3010-B246-EABD-C94A94123B26 linked against AF65F317-0A82-76B4-37A0-214DC22BA431, but 90E4E4EF-875E-4CB5-7EF1-28FFACCFC6B6 is loaded @OSKext.cpp:13026
Panicked task 0xffffff854983ce60: 3 threads: pid 106: kernelmanagerd
Backtrace (CPU 4), panicked thread: 0xffffff854984fe30, Frame : Return Address
0xffffffd094adb520 : 0xffffff800a89c00d mach_kernel : _handle_debugger_trap + 0x41d
0xffffffd094adb570 : 0xffffff800a9f5d85 mach_kernel : _kdp_i386_trap + 0x145
0xffffffd094adb5b0 : 0xffffff800a9e5763 mach_kernel : _kernel_trap + 0x533
0xffffffd094adb600 : 0xffffff800a83ba60 mach_kernel : _return_from_trap + 0xe0
0xffffffd094adb620 : 0xffffff800a89c3dd mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffd094adb740 : 0xffffff800a89bb96 mach_kernel : _panic_trap_to_debugger + 0x2b6
0xffffffd094adb7a0 : 0xffffff800b118649 mach_kernel : _panic + 0x54
0xffffffd094adb810 : 0xffffff800afcb394 mach_kernel : __ZN6OSKext29validateKCUUIDfromPrelinkInfoEPA16_h7kc_kindP12OSDictionaryPKc + 0x484
0xffffffd094adb930 : 0xffffff800afc8e5f mach_kernel : __ZN6OSKext21validateKCFileSetUUIDEP12OSDictionary7kc_kind + 0x2f
0xffffffd094adb960 : 0xffffff800afc869e mach_kernel : __ZN6OSKext12mapKCFileSetEPvmPP14mach_header_64xPmbS0_ + 0xb3e
0xffffffd094adb9e0 : 0xffffff800afd5e5c mach_kernel : __ZN6OSKext13loadKCFileSetEPKc7kc_kind + 0x26c
0xffffffd094adbc00 : 0xffffff800afd55b5 mach_kernel : __ZN6OSKext16loadFileSetKextsEP12OSDictionary + 0x2e5
0xffffffd094adbc60 : 0xffffff800afd3b53 mach_kernel : __ZN6OSKext13handleRequestEP4hostjPcjPS2_PjS3_S4_ + 0x13c3
0xffffffd094adbce0 : 0xffffff800afe732d mach_kernel : _kext_request + 0x1ad
0xffffffd094adbd70 : 0xffffff800a911f7b mach_kernel : _host_priv_server_routine + 0x22bb
0xffffffd094adbdc0 : 0xffffff800a876cf9 mach_kernel : _ipc_kmsg_send + 0x449
0xffffffd094adbe50 : 0xffffff800a88dd89 mach_kernel : _mach_msg_overwrite_trap + 0x2d9
0xffffffd094adbee0 : 0xffffff800a9caaf2 mach_kernel : _mach_call_munger64 + 0x272
0xffffffd094adbfa0 : 0xffffff800a83c246 mach_kernel : _hndl_mach_scall64 + 0x16

Process name corresponding to current thread (0xffffff854984fe30): kernelmanagerd
Boot args: -v keepsyms=1 dart=0 alcid=1 -no_compat_check kext-dev-mode=1 darkwake=0 shikigva=80 agdpmod=pikera -lilubetaall 

Mac OS version:
21A559

Kernel version:
Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
Kernel UUID: 19BD4E1B-0268-3EE0-BC66-91F035BC9429
KernelCache slide: 0x000000000a600000
KernelCache base:  0xffffff800a800000
Kernel slide:      0x000000000a610000
Kernel text base:  0xffffff800a810000
__HIB  text base: 0xffffff800a700000
System model name: iMac16,1 ()
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

**Comment by Sparkesy** [comment]
I also am experiencing the same issues as stated above with my gtx 770

**Comment by androwebgraphic** [comment]
Yesterday I installed Monterey over Big sur disk. It booted ok recognized gt710 but only 7mb of ram. animations were lagy. I find this patch applied it but when rebooted progress bar below apple came half-way and restarted. Couldn't boot to ssd. Unfortunately Monterey dropped support for all Nvidia graphics.

**Comment by lengmiguel** [comment]
The patch works perfectly for me.



![image](https://user-images.githubusercontent.com/22181854/138949174-e97a953d-e747-4f51-b89d-5e5134b3979c.png)

**Comment by Sparkesy** [comment]
> The patch works perfectly for me.
> 
> 
> 
> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/22181854/138949174-e97a953d-e747-4f51-b89d-5e5134b3979c.png)
> 
> 

Was there anything you did different in comparison with the instructions

**Comment by Sparkesy** [comment]
> Yesterday I installed Monterey over Big sur disk. It booted ok recognized gt710 but only 7mb of ram. animations were lagy. I find this patch applied it but when rebooted progress bar below apple came half-way and restarted. Couldn't boot to ssd. Unfortunately Monterey dropped support for all Nvidia graphics.

Same happening here if I choose the securebootmodel default although if I change it to disabled I get the following panic ![image](https://user-images.githubusercontent.com/55036076/138952133-80b47b2c-79c6-427a-8903-3f3282ed9696.jpeg)

**Comment by AO554** [comment]
Its been a few hours and I have had the system running perfectly for a few hours, I basically had to go and reinstall Monterey again so it would remove the patches, change my csr-active value to one that would allow me to make changes, reset my NVRAM, boot my Recovery partition, csutill disable both options, reboot back into my System Disk, rerun the patches and voila

**Comment by lengmiguel** [comment]
> > The patch works perfectly for me.
> > ![image](https://user-images.githubusercontent.com/22181854/138949174-e97a953d-e747-4f51-b89d-5e5134b3979c.png)
> 
> Was there anything you did different in comparison with the instructions

I followed the steps indicated

The securebootmodel I put it in the config.plist = Misc- Security as disable

Then csrutil disable for recovery

and in config.plist add csr-active-config ➤ EF0F0000

**Comment by androwebgraphic** [comment]
I used Clover 5138 version, it was from Big Sur ssd which was replaced by  Monterey and after direct install of Monterey it has boot . Maybe I should change in Clover configurator to make it work.Open core is to complicated to me and i never succeed while install Big Sur.

**Comment by Sparkesy** [comment]
Hi I just wanted to check is it the v1 or v2 patch I use as after using v2 twice now it's done what was said above and is now unusable

**Comment by lengmiguel** [comment]
> Hola, solo quería verificar si es el parche v1 o v2 que uso, ya que después de usar v2 dos veces, se hizo lo que se dijo anteriormente y ahora no se puede usar.


Hi I used v2 but I use opencore

**Comment by arcade33** [comment]
For those who say that they get problem with this patch 
all is working perfect for me with two hacks
GT 710 2GO 
CLOVER 5141 
<key>Boot</key>
	<dict>
		<key>Arguments</key>
		<string>keepsyms=1 alcid=9</string>
and

 <key>RtVariables</key>
	<dict>
		<key>BooterConfig</key>
		<string>0x28</string>
		<key>CsrActiveConfig</key>
		<string>0x867</string
![Capture d’écran 2021-10-29 à 07 21 27](https://user-images.githubusercontent.com/5526210/139380838-edb37c0c-8085-4c69-8c9c-43107b388eff.png)

![Capture d’écran 2021-10-29 à 07 30 39](https://user-images.githubusercontent.com/5526210/139380954-f8b9cf32-b122-4638-95eb-306caeee5fb4.png)
------------------------------------------------------------------------------
Second HACK 
CLOVER 5141
![Capture d’écran 2021-10-29 à 08 28 13](https://user-images.githubusercontent.com/5526210/139387458-76e7df53-26fe-46b9-8b3f-ac96fcfc5ada.png)

![Capture d’écran 2021-10-29 à 08 32 30](https://user-images.githubusercontent.com/5526210/139387469-9d533e8b-ba6d-46cd-bbec-0adab34a95ee.png)
![Capture d’écran 2021-10-29 à 08 31 55](https://user-images.githubusercontent.com/5526210/139387485-8ca84c70-1540-426c-823d-710f9e0ca721.png)

you can try that
![Capture d’écran, le 2021-10-29 à 08 55 20](https://user-images.githubusercontent.com/5526210/139389967-e5b32ffc-2c27-4828-ab63-11ac221c84bf.png)

**Comment by chenli1989** [comment]
> Strange, its every time I install the patch for my GT 740, it goes through the normal steps of renaming my boot drive, asks me to select it and then applies and Tells me to reboot. but whenever I'm trying to boot the patched disk, it just halts here
> 
> panic(cpu 4 caller 0xffffff800afcb394): System KC UUID 6A589D20-3010-B246-EABD-C94A94123B26 linked against AF65F317-0A82-76B4-37A0-214DC22BA431, but 90E4E4EF-875E-4CB5-7EF1-28FFACCFC6B6 is loaded @OSKext.cpp:13026 Panicked task 0xffffff854983ce60: 3 threads: pid 106: kernelmanagerd Backtrace (CPU 4), panicked thread: 0xffffff854984fe30, Frame : Return Address 0xffffffd094adb520 : 0xffffff800a89c00d mach_kernel : _handle_debugger_trap + 0x41d 0xffffffd094adb570 : 0xffffff800a9f5d85 mach_kernel : _kdp_i386_trap + 0x145 0xffffffd094adb5b0 : 0xffffff800a9e5763 mach_kernel : _kernel_trap + 0x533 0xffffffd094adb600 : 0xffffff800a83ba60 mach_kernel : _return_from_trap + 0xe0 0xffffffd094adb620 : 0xffffff800a89c3dd mach_kernel : _DebuggerTrapWithState + 0xad 0xffffffd094adb740 : 0xffffff800a89bb96 mach_kernel : _panic_trap_to_debugger + 0x2b6 0xffffffd094adb7a0 : 0xffffff800b118649 mach_kernel : _panic + 0x54 0xffffffd094adb810 : 0xffffff800afcb394 mach_kernel : __ZN6OSKext29validateKCUUIDfromPrelinkInfoEPA16_h7kc_kindP12OSDictionaryPKc + 0x484 0xffffffd094adb930 : 0xffffff800afc8e5f mach_kernel : __ZN6OSKext21validateKCFileSetUUIDEP12OSDictionary7kc_kind + 0x2f 0xffffffd094adb960 : 0xffffff800afc869e mach_kernel : __ZN6OSKext12mapKCFileSetEPvmPP14mach_header_64xPmbS0_ + 0xb3e 0xffffffd094adb9e0 : 0xffffff800afd5e5c mach_kernel : __ZN6OSKext13loadKCFileSetEPKc7kc_kind + 0x26c 0xffffffd094adbc00 : 0xffffff800afd55b5 mach_kernel : __ZN6OSKext16loadFileSetKextsEP12OSDictionary + 0x2e5 0xffffffd094adbc60 : 0xffffff800afd3b53 mach_kernel : __ZN6OSKext13handleRequestEP4hostjPcjPS2_PjS3_S4_ + 0x13c3 0xffffffd094adbce0 : 0xffffff800afe732d mach_kernel : _kext_request + 0x1ad 0xffffffd094adbd70 : 0xffffff800a911f7b mach_kernel : _host_priv_server_routine + 0x22bb 0xffffffd094adbdc0 : 0xffffff800a876cf9 mach_kernel : _ipc_kmsg_send + 0x449 0xffffffd094adbe50 : 0xffffff800a88dd89 mach_kernel : _mach_msg_overwrite_trap + 0x2d9 0xffffffd094adbee0 : 0xffffff800a9caaf2 mach_kernel : _mach_call_munger64 + 0x272 0xffffffd094adbfa0 : 0xffffff800a83c246 mach_kernel : _hndl_mach_scall64 + 0x16
> 
> Process name corresponding to current thread (0xffffff854984fe30): kernelmanagerd Boot args: -v keepsyms=1 dart=0 alcid=1 -no_compat_check kext-dev-mode=1 darkwake=0 shikigva=80 agdpmod=pikera -lilubetaall
> 
> Mac OS version: 21A559
> 
> Kernel version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 Kernel UUID: 19BD4E1B-0268-3EE0-BC66-91F035BC9429 KernelCache slide: 0x000000000a600000 KernelCache base: 0xffffff800a800000 Kernel slide: 0x000000000a610000 Kernel text base: 0xffffff800a810000 __HIB text base: 0xffffff800a700000 System model name: iMac16,1 () System shutdown begun: NO Panic diags file available: YES (0x0) Hibernation exit count: 0

@AO554 @Sparkesy @androwebgraphic 

Thanks to plugin author @chris1111  for his contribution! I have successfully typed the driver, now it can display normally🎉🎉🎉. Run into the same problems, and finally find the key problem. Hope the following program to help you!

I used v2 and opencore 0.7.5.

In recovery, the terminal executes the following two commands:
✅   `csrutil disable`

⚠️ Add `csr-active-config` as `EF0F0000` in config.plist not necessary. The following command is required:

✅   `csrutil authenticated-root disable`

‼️ Other steps are in accordance with the document!

✅   SecureBootModel ➤ Disabled

✅   Gatekeeper must be disable

✅   Run `Geforce Kepler patcher`

🎉🎉🎉

![image](https://user-images.githubusercontent.com/8178749/139415259-553502ee-c043-4805-9f23-f0eb6836b993.png)

**Comment by Sparkesy** [comment]
> > Strange, its every time I install the patch for my GT 740, it goes through the normal steps of renaming my boot drive, asks me to select it and then applies and Tells me to reboot. but whenever I'm trying to boot the patched disk, it just halts here
> 
> > 
> 
> > panic(cpu 4 caller 0xffffff800afcb394): System KC UUID 6A589D20-3010-B246-EABD-C94A94123B26 linked against AF65F317-0A82-76B4-37A0-214DC22BA431, but 90E4E4EF-875E-4CB5-7EF1-28FFACCFC6B6 is loaded @OSKext.cpp:13026 Panicked task 0xffffff854983ce60: 3 threads: pid 106: kernelmanagerd Backtrace (CPU 4), panicked thread: 0xffffff854984fe30, Frame : Return Address 0xffffffd094adb520 : 0xffffff800a89c00d mach_kernel : _handle_debugger_trap + 0x41d 0xffffffd094adb570 : 0xffffff800a9f5d85 mach_kernel : _kdp_i386_trap + 0x145 0xffffffd094adb5b0 : 0xffffff800a9e5763 mach_kernel : _kernel_trap + 0x533 0xffffffd094adb600 : 0xffffff800a83ba60 mach_kernel : _return_from_trap + 0xe0 0xffffffd094adb620 : 0xffffff800a89c3dd mach_kernel : _DebuggerTrapWithState + 0xad 0xffffffd094adb740 : 0xffffff800a89bb96 mach_kernel : _panic_trap_to_debugger + 0x2b6 0xffffffd094adb7a0 : 0xffffff800b118649 mach_kernel : _panic + 0x54 0xffffffd094adb810 : 0xffffff800afcb394 mach_kernel : __ZN6OSKext29validateKCUUIDfromPrelinkInfoEPA16_h7kc_kindP12OSDictionaryPKc + 0x484 0xffffffd094adb930 : 0xffffff800afc8e5f mach_kernel : __ZN6OSKext21validateKCFileSetUUIDEP12OSDictionary7kc_kind + 0x2f 0xffffffd094adb960 : 0xffffff800afc869e mach_kernel : __ZN6OSKext12mapKCFileSetEPvmPP14mach_header_64xPmbS0_ + 0xb3e 0xffffffd094adb9e0 : 0xffffff800afd5e5c mach_kernel : __ZN6OSKext13loadKCFileSetEPKc7kc_kind + 0x26c 0xffffffd094adbc00 : 0xffffff800afd55b5 mach_kernel : __ZN6OSKext16loadFileSetKextsEP12OSDictionary + 0x2e5 0xffffffd094adbc60 : 0xffffff800afd3b53 mach_kernel : __ZN6OSKext13handleRequestEP4hostjPcjPS2_PjS3_S4_ + 0x13c3 0xffffffd094adbce0 : 0xffffff800afe732d mach_kernel : _kext_request + 0x1ad 0xffffffd094adbd70 : 0xffffff800a911f7b mach_kernel : _host_priv_server_routine + 0x22bb 0xffffffd094adbdc0 : 0xffffff800a876cf9 mach_kernel : _ipc_kmsg_send + 0x449 0xffffffd094adbe50 : 0xffffff800a88dd89 mach_kernel : _mach_msg_overwrite_trap + 0x2d9 0xffffffd094adbee0 : 0xffffff800a9caaf2 mach_kernel : _mach_call_munger64 + 0x272 0xffffffd094adbfa0 : 0xffffff800a83c246 mach_kernel : _hndl_mach_scall64 + 0x16
> 
> > 
> 
> > Process name corresponding to current thread (0xffffff854984fe30): kernelmanagerd Boot args: -v keepsyms=1 dart=0 alcid=1 -no_compat_check kext-dev-mode=1 darkwake=0 shikigva=80 agdpmod=pikera -lilubetaall
> 
> > 
> 
> > Mac OS version: 21A559
> 
> > 
> 
> > Kernel version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 Kernel UUID: 19BD4E1B-0268-3EE0-BC66-91F035BC9429 KernelCache slide: 0x000000000a600000 KernelCache base: 0xffffff800a800000 Kernel slide: 0x000000000a610000 Kernel text base: 0xffffff800a810000 __HIB text base: 0xffffff800a700000 System model name: iMac16,1 () System shutdown begun: NO Panic diags file available: YES (0x0) Hibernation exit count: 0
> 
> 
> 
> @AO554 @Sparkesy @androwebgraphic 
> 
> 
> 
> Thanks to plugin author @chris1111  for his contribution! I have successfully typed the driver, now it can display normally🎉🎉🎉. Run into the same problems, and finally find the key problem. Hope the following program to help you!
> 
> 
> 
> In recovery, the terminal executes the following two commands:
> 
> ✅   `csrutil disable`
> 
> 
> 
> ⚠️ Add `csr-active-config` as `EF0F0000` in config.plist not necessary. The following command is required:
> 
> 
> 
> ✅   `csrutil authenticated-root disable`
> 
> 
> 
> ‼️ Other steps are in accordance with the document!

What should go in the config instead then also what securebootmodel needs to be used

**Comment by arcade33** [comment]
this morning i make beta 1 Monterey final !!!!
with CLOVER 5141 , i don't speak about OPEN CORE 
with this value  
![Capture d’écran 2021-10-29 à 11 59 22](https://user-images.githubusercontent.com/5526210/139416285-dcf77e87-9cdb-4b0e-b90c-bbfee9ed02aa.png)
![Capture d’écran 2021-10-29 à 11 44 40](https://user-images.githubusercontent.com/5526210/139416304-8ce40aeb-fa7f-4834-b00e-a6353a183a82.png)

![Capture d’écran 2021-10-29 à 11 43 48](https://user-images.githubusercontent.com/5526210/139416346-167b3f7a-d7ff-48cc-ad70-88ab92b884b2.png)
![Capture d’écran 2021-10-29 à 11 48 43](https://user-images.githubusercontent.com/5526210/139416384-faceeadf-ec51-47a7-a7d6-ca8a97623fc4.png)
![Capture d’écran 2021-10-29 à 12 12 22](https://user-images.githubusercontent.com/5526210/139417851-6493f920-2496-41af-a5fe-5251b43de3e6.png)

![Capture d’écran 2021-10-29 à 12 12 47](https://user-images.githubusercontent.com/5526210/139417860-e0f7972a-eb71-4605-af76-bff730fa677b.png)
