### ISSUE TITLE
macOS Ventura

### ISSUE THREAD

**Issue by ghost** [chris1111/Geforce-Kepler-patcher#41]
Is there a chance to successfully install the N card under macOS Ventura?

**Comment by chris1111** [comment]
No! not for now, Please wait

**Comment by ghost** [comment]
thanks a lot for your answer

**Comment by borisorlov21** [comment]
Looking forward to the new patch On Mac Ventura Chris make us happy⚡️

**Comment by ghost** [comment]
Currently using for GK208 on Monterey - working well
Eagerly waiting for Ventura! Thanks a lot for your hard work, Chris.

**Comment by tobias-beale** [comment]
Hi Chris,

I'm a big fan of your work. Would donations help to give you the time to work on making Kepler work in Ventura? Or is there another bottleneck I'm not aware of.

I'm running MacOS in KVM. Would it make more sense for me to get an RX 570? Would it just work out of the box in Ventura?

I'm new to this so please excuse my ignorance.

Thanks

Tobias

**Comment by Touchiestworm** [comment]
Yes rx 570 works OOB with whatevergreen and lilu kext

**Comment by darkcode78** [comment]
Hi Chris, how are you? A query that we are all asking ourselves. Will a patch be available for Kepler GPUs on Ventura?

**Comment by chris1111** [comment]
> Hi Chris, how are you? 

Iam good

> A query that we are all asking ourselves. Will a patch be available for Kepler GPUs on Ventura?

Not for this program!
