### ISSUE TITLE
Any chance with Maxwell Gtx 850M

### ISSUE THREAD

**Issue by 5l1v3r1** [chris1111/Geforce-Kepler-patcher#43]
Thank you for the patch. Is there any chance for this script to work on 850M Gtx 4 Gb Ddr 3 Model? I want to use cuda and opencv and with igpu hd4600 i cant use them (currently monterrey on my n550jk asus recognizes this as the main gpu with modification).

**Comment by chris1111** [comment]
GTX 850m is GM107 graphics processor , not a Kepler architecture; anyway, configuring a laptop Graphics card has nothing to do with this patch, it falls under configuring a Hackintosh
