### ISSUE TITLE
Patch unsuccessful

### ISSUE THREAD

**Issue by Jissee** [chris1111/Geforce-Kepler-patcher#45]
I am using macOS 12.1 and quadro K4000. I disabled sip and gatekeeper and used your patcher. Nothing was wrong at installation and it succeeded. But after reboot, the system cannot be loaded. The log kept on rolling. I had shot a video of what was showing. Can you help me to figure out what was wrong please?

**Comment by testhmf33** [comment]
quadro K4000 isn't a KEPLER CARD , so you can't use tis patch

**Comment by Jissee** [comment]
> 

So could you tell me what should I do to save my hackintosh PLEASE?

**Comment by Jissee** [comment]
> quadro K4000 isn't a KEPLER CARD , so you can't use tis patch

So could you tell me what should I do to save my hackintosh PLEASE?

**Comment by testhmf33** [comment]
add nv_disabe=1 in your boot args 
if you have an IGPU try to boot with it
google is tour friend

**Comment by Jissee** [comment]
> add nv_disabe=1 in your boot args if you have an IGPU try to boot with it google is tour friend

Unfortunately I don't have an IGPU :(

I searched the web and found that k4000 does use kepler architecture and there was something wrong with my operation. After I reinstall it, another problem occurred. The GPU truned to "NVIDIA Chip model 3MB". It could be recognised before the patch.

**Comment by Jissee** [comment]
So is it confirmed that k4000 is impossible to be used in macOS 12？

**Comment by chris1111** [comment]
https://www.gpuzoo.com/GPU-NVIDIA/Quadro_K4000.html

**Comment by danydc** [comment]
@Jissee It's possible!! I had the same problems but I tried adding to boot-arg the following: nvda_drv=1 (it is supposed to activate the web drivers) and works!
![Captura de Pantalla 2022-07-20 a las 14 34 14](https://user-images.githubusercontent.com/13364722/179984615-77593f04-6ce8-4dfb-bc7e-07bf2a04d9dd.png)
