### ISSUE TITLE
Is this patch required for the final version (versus the beta)

### ISSUE THREAD

**Issue by TS200010** [chris1111/Geforce-Kepler-patcher#46]
Is this needed in the final Monterey version released by Apple? I ask as I see conflicting information floating around. The Opencore docs say all Kepler support has been dropped but various other sources say they have successful installed on GT 740.

**Comment by chris1111** [comment]
Latest Update 06 August 2022 FIX kepler patcher V4
 12.5 (21G72) - Login loop is resolved
![Screen Shot 2022-08-06 at 9 24 19 AM](https://user-images.githubusercontent.com/6248794/183254185-4c94e3bf-182f-44ad-9cc9-2a447b4160d9.png)
