### ISSUE TITLE
Browsers crashing

### ISSUE THREAD

**Issue by Touchiestworm** [chris1111/Geforce-Kepler-patcher#47]
Dell optiplex 780
C2q with gt730 and OC 8.1 legacy smbios imac 17,1 with Monterey. 
Ive disabled sip (still disabled or no boot)and installed the patch and everythings working accept all browsers crash except safari . Ive tried opera and firefox as well and they crash too. 
Safari cant get location for hulu(never has been able too)so i use chrome to watch hulu b4 i updated from big sur to monterey. 
at first i thought is was sip related but used same efi to boot catalina and chrome works fine.

Is chrome closing cause sip is diabled in monty?
How can i fix this? 
Do you know of a browser that streams hulu that dont crash with the patch?

**Comment by chris1111** [comment]
Try SIP `00080000`

**Comment by Touchiestworm** [comment]
Your awesome dude. That worked. 

one more thing. 
after installing the patch it renames my ssd to monterey-disk but in the picker it still shows its old name big sur ssd. 
Ive cleaned/reset nvram and renamed the other containers to mach monterey-disk but still shows big sur

**Comment by chris1111** [comment]
you can change the name monterey-disk for any other name
