### ISSUE TITLE
Unable to Download kext Form OpenCore Configurator & SDK From Visual Studio

### ISSUE THREAD

**Issue by Samanosuke2020** [chris1111/Geforce-Kepler-patcher#49]
after patching Unable to download kext from open core configurator , it simply freezes.
same issue in Visual Studio unable to download or update android SDK,

**Comment by chris1111** [comment]
Use csr-active-config 

00080000

**Comment by Samanosuke2020** [comment]
modified csr value to 00080000 , but not works, :(
![Screenshot 2022-07-19 at 1 39 29 AM](https://user-images.githubusercontent.com/62993380/179608590-cb875e3f-9dcb-47f6-b358-73e167ac282e.png)

**Comment by chris1111** [comment]
Reset Nvram

**Comment by Samanosuke2020** [comment]
Everything reset, clean, etc done ,  csrutil clear in recovery and reconfigured , still problem persist
