### ISSUE TITLE
Geforce-Kepler-Patcher for Monterey 12.5 broken?

### ISSUE THREAD

**Issue by ferhatmeric** [chris1111/Geforce-Kepler-patcher#51]
Hi, 

i've setup all Monterey versions (12.0, 12.1, 12.2, 12.3, 12.4) and Geforce-Kepler patcher works fine. 

But after fresh installing Monterey 12.5 Geforce-Kepler patch doesn't work. After installing Geforce-Kepler patch i get login screen and when I enter my password screen freezes. 

I tried to update opencore boot loader and all kext files but no success. 

Is there any working Geforce-Kepler patch for Monterey 12.5?

**Comment by chris1111** [comment]
Readme Warning: This app not working after macOS Monterey 12.5 Beta 2
Issue Login screen loop

Revert to 12.4

**Comment by chris1111** [comment]
FIX with V4 see update

**Comment by ferhatmeric** [comment]
v4 works. thanks.
