### ISSUE TITLE
not start after installing Geforce-Kepler-patcher-V4

### ISSUE THREAD

**Issue by tyagnesh** [chris1111/Geforce-Kepler-patcher#53]
I do have
Motherboard : Intel DH61WW
CPU : i3-3220
Graphics : GT 710
Here I am sharing my EFI as well

[EFI (1).zip](https://github.com/chris1111/Geforce-Kepler-patcher/files/9297779/EFI.1.zip)

**Comment by chris1111** [comment]
The start or the shutdown has nothing to do with the patcher
we deal with the problem of the patcher and not config or OpenCore setup

**Comment by tyagnesh** [comment]
But it was post install of Kepler Kepler-patcher-V4,

**Comment by testhmf33** [comment]
no problem with the Kepler-patcher-V4  

gatekeeper and sip must be disabled 
![Capture d’écran 2022-08-10 à 14 52 58](https://user-images.githubusercontent.com/91620557/183907774-4ed9dcea-fd7b-43f0-ae9c-17589ab11e4d.png)
![Capture d’écran 2022-08-10 à 14 55 32](https://user-images.githubusercontent.com/91620557/183907783-4bbb9f09-2679-489d-b5dd-2492d1122273.png)

**Comment by tyagnesh** [comment]
@testhmf33 I am not saying there is problem in Kepler but
I did same as instructed but still same

**Comment by tyagnesh** [comment]
Here is the screenshot of verbose 
![Screenshot_20220812-190255_Video Player](https://user-images.githubusercontent.com/18632492/184368379-94d6384f-3a79-4c09-ba0c-6fb4e491d1ea.jpg)

**Comment by chris1111** [comment]
3 time changing title 
Try Reset Nvram
What is the version of Monterey exactly
