### ISSUE TITLE
Does v4. works with Monterey 12.5.1?

### ISSUE THREAD

**Issue by lepemepe** [chris1111/Geforce-Kepler-patcher#54]
Thanx!!

**Comment by xdccrlz** [comment]
Yes, it does) GKP give error 75, but after reboot it's works!

**Comment by chris1111** [comment]
I don't have any GKP error here

Yes it work

![scree648](https://user-images.githubusercontent.com/6248794/185611527-02d8ad23-ca4e-48f7-8939-2accf5fd7a4d.png)
![scree649](https://user-images.githubusercontent.com/6248794/185611529-485dc383-5642-40bb-9285-e10f0e02fcc5.png)
