### ISSUE TITLE
Wallpaper Glitch

### ISSUE THREAD

**Issue by kard8** [chris1111/Geforce-Kepler-patcher#55]
Great job with the Patch. Truly a lifesaver with which my graphic card could breath a new life.

I have these glitchy effects here. Seems to affect the Wallpapers in the Settings app only. The glitch does not disappear during reboots. Other images when set as background are not affected. (the file was jpeg).

Running macOS 12.4 with the v3 Kepler patch
CPU : i5-9400F
GPU : GT-710 2GB

Can You please help me with this issue.

![Screenshot 2022-08-24 at 12 47 47 AM](https://user-images.githubusercontent.com/110168813/186247105-e6d7ae13-39e6-487e-bd7c-4cd2464a0f45.png)

**Comment by chris1111** [comment]
I really don't know about that ? Never see this, my suggestion is to update to latest Monterey then try V4

**Comment by testhmf33** [comment]
take a look in the setting of your bios 
i've got this problem a long time ago 
if i've a good memory , my bios setting  was on igpu and not on pci

**Comment by kard8** [comment]
Thank you for replying.

@chris1111 
I will try to update to v4. 

@testhmf33 I dont have an iGPU as myCPU is "-F" Version  (without iGPU")

Found this post on TonyMacx86
https://www.tonymacx86.com/threads/heic-dynamic-wallpaper-corruption-in-catalina.285716/post-2022171

>should be IGPU issue, enable the IGPU
IGPU provide hardware acccleration for HEIF and HEVC format

**Comment by kard8** [comment]
Resolved:

Solution # 1

Found out that glitch appears in a specific resolution, Changed the monitor resolution and the glitch does not appear.

Problematic Resolution : 1600x900

Solution # 2

Changed the resolution of wallpaper in Preview to fit my current resolution. works like a charm. Got dynamic wallpaper too.

[Monterey Graphic 1.heic.zip](https://github.com/chris1111/Geforce-Kepler-patcher/files/9413931/Monterey.Graphic.1.heic.zip)
