### ISSUE TITLE
I have gt730 ddr5 2gb graphic card but maximum resolution I can set is 1024 x 768, after installing Kepler V3 my display going to hig resolution how to fix that to 1024x768

### ISSUE THREAD

**Issue by durgaeagle99** [chris1111/Geforce-Kepler-patcher#56]
I installed MAC MONTEREY 12.4 
I have gt730 ddr5 2gb graphic card but maximum resolution I can set is 1024 x 768, after installing Kepler V3 my display going to hig resolution how to fix that to 1024x768.

**Comment by durgaeagle99** [comment]
I installed MAC Monterey 12.4

**Comment by chris1111** [comment]
your suppose to have max resolution available

**Comment by durgaeagle99** [comment]
Means 1024x768 is not supported......?

**Comment by durgaeagle99** [comment]
> your suppose to have max resolution available

My Monitors resolution is Max 1024x768

**Comment by chris1111** [comment]
If you have max 1024x768 You can not adjust more then that

**Comment by durgaeagle99** [comment]
> If you have max 1024x768 You can not adjust more then that

No my monitor automatically going to sleep mode off i connected it to my android tv then it's showing display but not to my monitor how can I set default of 1024x768
