### ISSUE TITLE
If you have a Real MAC use [OCLP]？

### ISSUE THREAD

**Issue by jackacc** [chris1111/Geforce-Kepler-patcher#57]
Welcome Geforce Kepler patcher

Build by chris1111
Created from Script Debuger
Credit: Base on [Jackluke methode](https://github.com/jacklukem), Find binaries [KhronoKernel](https://github.com/dortania/PatcherSupportPkg)
For Hackintosh with Graphics cards based on Kepler architecture only!
If you have a Real MAC use [OCLP]？
ASUSK50ID    Graphics GT320M  ，Most series， 9400GT   Etc.?

**Comment by chris1111** [comment]
were is the issue
