### ISSUE TITLE
Help Wanted: Geforece-Kepler-Patcher-SIP-OC-Monterey

### ISSUE THREAD

**Issue by pratappal** [chris1111/Geforce-Kepler-patcher#58]
Hello Experts, 

I'm new to this community and need some assistance please -
I've successfully installed Monterey 12.5.1 using OC 0.8.3 on legacy GA-X58a/i7 920/GT 710 Then with SIP EF0F0000, also successfully applied Geforce-Kepler-Patcher - up to this all good. When i changed the SIP to 00080000 and it is not booting anymore - resulting some kernel panic. Even if i reset the SIP to EF0F0000 no luck.

Does it mean i have to keep SIP EF0F0000 forever to keep my GT 710 working on Monterey - is it ok?

Please respond as possible - any help is appricated.

Regards, pp

**Comment by chris1111** [comment]
did you apply a reset NVRAM after the change?

**Comment by pratappal** [comment]
Thanks for responding - yes i did however with reset, EFI/NVRAM/nvram.plist cleared but a nvram.used there - should i remove nvram.used as well?
