### ISSUE TITLE
Black screen iOS Simulator and xcode interface builder on monterey

### ISSUE THREAD

**Issue by dodync** [chris1111/Geforce-Kepler-patcher#60]
First I need to say thank you for this patch.
I use this patch for my GT 710 1Gb. It works well on monterey but with a few minor issues:

- it seems after running a gpu intensive program, in my experience is roblox, I experience lag with my mouse cursor. Reboot fix this problem.
- iOS simulator 15.4 and 15.5 shows black screen. As temporary solution, I use iOS Simulator 15.0 or real device.
- I use xcode 13.4.1. The interface builder is black and broken, unusable. I can avoid it by using swiftui. No solution right now.

**Comment by chris1111** [comment]
thanks

See this for [iOS simulator](https://github.com/chris1111/Geforce-Kepler-patcher/issues/29#issuecomment-1221525615)
