### ISSUE TITLE
Monterey 12.6

### ISSUE THREAD

**Issue by lepemepe** [chris1111/Geforce-Kepler-patcher#61]
Is the patch compatible? Thanx!

**Comment by testhmf33** [comment]
Yes 
![capt1409](https://user-images.githubusercontent.com/91620557/190843341-f69991b1-5305-4d28-b4c7-b05ced7bc831.png)

**Comment by BillDH2k** [comment]
Same question. Which patcher to use? V3 or V4 for 12.6? 

Follow up: knew the answer now. Any official release would be newer than the beta release.

**Comment by chris1111** [comment]
> Same question. Which patcher to use? V3 or V4 for 12.6?
> 
> Follow up: knew the answer now. Any official release would be newer than the beta release.


Exactly 12.6 is newer then the 12.5 beta
So use the V4
