### ISSUE TITLE
Is there a way to uninstall the patch here?

### ISSUE THREAD

**Issue by i0Ek3** [chris1111/Geforce-Kepler-patcher#63]
Hi Chris, thank you for your work, I've been use this patch until 12.4, that's really awesome. And now I don't have a spare 4K monitor, so I don't need my HP GT630(2G) dGPU anymore, so I want to remove these patches. But I found that I can't remove it directly, because /S/L/E is read-only, so I was thinking, can I remove it through Recovery or some way? Do you have any suggestions? Thank you again.

**Comment by i0Ek3** [comment]
My guess should be correct, and my operation steps are as follows: 

1. Modify the relevant parameters of config.plist 
2. Delete the corresponding kexts and bundles under Recovery system
3. Shutdown and remove the dGPU
4. Adjust the BIOS related settings after booting(i.e. Secure Boot must be disable)

After that, the iGPU can be used normally.

**Comment by chris1111** [comment]
That's not really the good way, I Build a Uninstaller tonight
I will test before then publish a release tonight

**Comment by i0Ek3** [comment]
@chris1111 Oh, thank you so much, looking forward to your release.

**Comment by chris1111** [comment]
OK Done [Release V5](https://github.com/chris1111/Geforce-Kepler-patcher/releases/tag/V5)
[Commit](https://github.com/chris1111/Geforce-Kepler-patcher/commit/6549863986f6a695e6d19ffbc10ce735f5320e3e)
[Commit](https://github.com/chris1111/Geforce-Kepler-patcher/commit/f3beb376f067ddb37e5ed75dac1560cad39182bc)

![Screenshot 2022-09-22 at 4 04 34 PM](https://user-images.githubusercontent.com/6248794/191840580-0134d64b-b764-4b60-bbdf-1e7d17da13c7.png)
