### ISSUE TITLE
OCLP  and this patcher

### ISSUE THREAD

**Issue by madmax2** [chris1111/Geforce-Kepler-patcher#65]
Is it required to have OCLP installed as well as using this patcher for patching kepler to work with monterey / ventura?

Confused about OCLP and this patcher's difference.

**Comment by chris1111** [comment]
Not working in Ventura then OCLP is not required for this patcher, this patcher is only for Monterey

**Comment by madmax2** [comment]
@chris1111
Okay leaving Ventura aside..

What is the difference between OCLP and this patcher?
Is OCLP also able to get kepler to work with monterey?

Do we need to use both OCLP or just this patcher to get kepler to work with monterey.

Still confused about your answer
