### ISSUE TITLE
Help Wanted: not support macOS Ventura?

### ISSUE THREAD

**Issue by RockRockWhite** [chris1111/Geforce-Kepler-patcher#67]
Apple released macOS Ventura today.
Does this tools support Ventura now? Or just because I installer patch in a wrong way?

**Comment by RockRockWhite** [comment]
I had checked the issues and got the answer - no.

**Comment by RockRockWhite** [comment]
So when will this tools support Ventura? I really need it.

**Comment by chris1111** [comment]
https://github.com/chris1111/Geforce-Kepler-patcher/issues/66

**Comment by RockRockWhite** [comment]
Thanks.
