### ISSUE TITLE
Ventura Support

### ISSUE THREAD

**Issue by kcj83** [chris1111/Geforce-Kepler-patcher#68]
Chris, now that Ventura 13.0 is released, we are looking forward to your next update to support our Keplers with this new release.

Also, if there is a way to donate to you for this project, ie. patreon etc. please let me know I'm happy to donate to you for this great work you're doing.

We all appreciate you and this hard work to make this happen Chris. Keep it up!!!

Best,
Kris (kcj83)
![Untitled](https://user-images.githubusercontent.com/79729347/197832703-93339aae-3008-42e8-bdb9-d8f4e6e1a42a.png)

**Comment by chris1111** [comment]
Thanks 
you can donate to [my profile](https://github.com/chris1111)
