### ISSUE TITLE
Ventura Final Os patch

### ISSUE THREAD

**Issue by jesusma32** [chris1111/Geforce-Kepler-patcher#69]
Hi Criss, thanks for your incredible work.

Maybe possible a ventura patch for Kepler?

Thanks in advance

**Comment by chris1111** [comment]
thanks @jesusma32 maybe? When I have spare time to adapt the logic of macOS 13

**Comment by methanoid** [comment]
Can the work OCLP has done getting Kepler working be leveraged??
