### ISSUE TITLE
Updates and such due to securebootmodel and SIP

### ISSUE THREAD

**Issue by Sparkesy** [chris1111/Geforce-Kepler-patcher#7]
I was wondering if there is any way of retaining update functionality and such since using the Disabled securebootmodel and after disabling SIP as when I try to change these settings to something that will allow for updates my system fails to boot yet when I revert it is fine

**Comment by chris1111** [comment]
There is no way  booting Snapshot disk without csrutil authenticated-root disable 
(csr-active-config ➤ EF0F0000
