### ISSUE TITLE
Kernel panic after enable SIP

### ISSUE THREAD

**Issue by batero2000** [chris1111/Geforce-Kepler-patcher#72]
Hi, I just want to clarify that I think this maybe the problem, but I'm uncertain about the problem and I thought somebody had this issue maybe.

So, I installer this Kepler patch showing on OCLP app (Ventura system), everything fine until now, boot perfect.

Yesterday I wanted to re enable SIP, and got this kernel panic:

![screeny](https://user-images.githubusercontent.com/14956589/205318415-0b6279ee-d2e9-4841-ac1d-e5db901a9c25.jpg)

It says something about "trap at 0xfff(...), type 14=page fault, registers: bla bla", that is the best screen I got because it reboots so fast.

So, I re disable SIP, but no success, still the same kernel panic :( .

Does anyone know what that means? Did anyone have this issue? Pls help.

**Comment by chris1111** [comment]
Reset NVRAM openCore

![02144237](https://user-images.githubusercontent.com/6248794/205321595-eec0b500-5bae-49a6-98d1-7ef6adb6392a.png)

**Comment by batero2000** [comment]
> Reset NVRAM openCore
> 
> ![02144237](https://user-images.githubusercontent.com/6248794/205321595-eec0b500-5bae-49a6-98d1-7ef6adb6392a.png)

I already did that a couple times, no fix :(

**Comment by chris1111** [comment]
probably not a good way

**Comment by batero2000** [comment]
> probably not a good way

I did realize that after I disable SIP and reboot, csrutil status still showing as on. And I can't boot macOS with SIP enable because of OCLP patch (kernel panic).

Even though I cleared and disable csrutil, when I type `nvram csr-active-config` the output value is ` E7030000`

**Comment by chris1111** [comment]
you need `EF0F0000`

**Comment by batero2000** [comment]
> you need `EF0F0000`

Thanks mate, working like a charm. I didn't know exactly what code use for csrutil.

Cleaned NVRAM and boot into the OS ;).
