### ISSUE TITLE
 Monterey 12.6.1 safari （16.2）have bug

### ISSUE THREAD

**Issue by starlifezzz** [chris1111/Geforce-Kepler-patcher#73]
system version：Monterry 12.6.1
GPU：gt710

safari come 16.1 update 16.2 don't work

I found that there will be problems when loading js, showing that the page is loaded multiple times. Uninstall the patch, the browser is normal

**Comment by testhmf33** [comment]
Update to Monterey 12.6.2  and patch with V5 
all is working like a charm here 
![Capture d’écran 2022-12-16 à 07 38 15](https://user-images.githubusercontent.com/91620557/208039175-f495cc2e-d5d7-457f-be72-e963a26f523f.png)

**Comment by starlifezzz** [comment]
God, I'm a little confused😂, I'm also using v5, I uninstalled the patch here, safari is normal, for testing I deleted all the extensions of safari. Thank you for your reply, I will look into the problem again

![image](https://user-images.githubusercontent.com/32615040/208046249-28008895-0939-444f-a605-253be52f900b.png)
![截屏2022-12-16 15 30 52](https://user-images.githubusercontent.com/32615040/208046449-da969408-3294-4f35-a20b-98a573fc8597.png)

**Comment by starlifezzz** [comment]
Found the reason, Apple idiot
Check whether the features of Safari are enabled or not in "Development-Experimental Features"
It was found that the two features of GPU Process: DOM Rendering and GPU Process: WebGL were turned off


source：
https://www.v2ex.com/t/898945#reply11

**Comment by iChris93** [comment]
> Found the reason, Apple idiot Check whether the features of Safari are enabled or not in "Development-Experimental Features" It was found that the two features of GPU Process: DOM Rendering and GPU Process: WebGL were turned off
> 
> source： https://www.v2ex.com/t/898945#reply11

This issue is back with Safari 16.5.2 and there is no longer an option for GPU Process: WebGL so I cannot seem to fix this. Any suggestions?

**Comment by iChris93** [comment]
Can this be re-opened?

**Comment by chris1111** [comment]
> > Found the reason, Apple idiot Check whether the features of Safari are enabled or not in "Development-Experimental Features" It was found that the two features of GPU Process: DOM Rendering and GPU Process: WebGL were turned off
> > source： https://www.v2ex.com/t/898945#reply11
> 
> This issue is back with Safari 16.5.2 and there is no longer an option for GPU Process: WebGL so I cannot seem to fix this. Any suggestions?


I will fix when I am back of my whistler trip
