### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by lepemepe** [chris1111/Geforce-Kepler-patcher#74]
Hi! How can I uninstall the patch? In order to change my GT-710 to a RX 580, so I need to uninstall the patch but I dunno how, thanx!

**Comment by chris1111** [comment]
![Screenshot 2023-02-13 at 5 17 22 AM](https://user-images.githubusercontent.com/6248794/218431618-a73e3bba-b7e5-44b6-8e1f-bfdb80fb21d6.png)
