### ISSUE TITLE
Simulator Black Screen After install the Patcher

### ISSUE THREAD

**Issue by IrvingGuerra** [chris1111/Geforce-Kepler-patcher#75]
![Captura de Pantalla 2023-02-25 a la(s) 12 28 40](https://user-images.githubusercontent.com/37481550/221373657-4db9801b-002b-4391-8c3a-5d80f8165d31.png)

**Comment by IrvingGuerra** [comment]
![Captura de Pantalla 2023-02-25 a la(s) 12 29 50](https://user-images.githubusercontent.com/37481550/221373688-c3c91b8f-52ce-448f-aa81-7faf8b247e44.png)

And sometimes the simulator is bugged, with blacks squares and rectangles

**Comment by chris1111** [comment]
https://github.com/chris1111/Geforce-Kepler-patcher/issues/29#issuecomment-1221525615

**Comment by IrvingGuerra** [comment]
![Captura de Pantalla 2023-02-25 a la(s) 12 35 09](https://user-images.githubusercontent.com/37481550/221373920-86735897-779f-4cd4-b9a9-f1ecec2de389.png)

@chris1111 not working with Xcode 14.2. 
Should I use an old version?

**Comment by IrvingGuerra** [comment]
@chris1111 Also, I use a XEON E5, it does not have graphics included.

What should I do?

**Comment by chris1111** [comment]
> @chris1111 Also, I use a XEON E5, it does not have graphics included.
> 
> What should I do?

Try an older Xcode version?
