### ISSUE TITLE
Xcode Simulator Go Blank on Monterey 

### ISSUE THREAD

**Issue by dhanwanit** [chris1111/Geforce-Kepler-patcher#76]
Hey i have installed  monterey on my Haswell Machine with Nvidia GEforce GT 730. Everything worked fine but when i tried to open Xcode simulator in 14.2 and 14.3. it's show black screen.
if i revert the patch it worked without it. Please help me.
![Screenshot 2023-04-09 at 4 20 04 PM](https://user-images.githubusercontent.com/39329665/230768353-160774c2-4033-4e8b-9ff4-58ef145158a9.png)
![Screenshot 2023-04-09 at 4 20 42 PM](https://user-images.githubusercontent.com/39329665/230768531-da4aea81-3999-4bc4-8065-b4091b7953bc.png)

**Comment by chris1111** [comment]
[same strory](https://github.com/chris1111/Geforce-Kepler-patcher/issues/29)

**Comment by dhanwanit** [comment]
> [same strory](https://github.com/chris1111/Geforce-Kepler-patcher/issues/29)

Yes i checked but did not help , i am still getting black screen issue on my Monterey Xcode 14.2  .
And when i am using intel integrated graphic i got only 4 mb  can you please tell me how can i increase the 4 mb

**Comment by chris1111** [comment]
> > [same strory](https://github.com/chris1111/Geforce-Kepler-patcher/issues/29)
> 
> Yes i checked but did not help , i am still getting black screen issue on my Monterey Xcode 14.2 . And when i am using intel integrated graphic i got only 4 mb can you please tell me how can i increase the 4 mb

Try 

`sudo defaults write /Library/Preferences/com.apple.security.libraryvalidation.plist DisableLibraryValidation -bool true`

Let me known?

**Comment by chris1111** [comment]
I try its not work for now, Iam not find a good solution
