### ISSUE TITLE
Safari 16.5.2 broken

### ISSUE THREAD

**Issue by iChris93** [chris1111/Geforce-Kepler-patcher#78]
Safari reports "A problem repeatedly occurred with" after updating Safari to 16.5.2. The previous fix of turning on the two experimental features of GPU Process: DOM Rendering and GPU Process: WebGL no longer works.

**Comment by chris1111** [comment]
> Safari reports "A problem repeatedly occurred with" after updating Safari to 16.5.2. The previous fix of turning on the two experimental features of GPU Process: DOM Rendering and GPU Process: WebGL no longer works.


I will fix when I am back of my whistler trip

**Comment by chris1111** [comment]
No issue here Geforce Kepler patcher-V7
Monterey Version 12.6.8 (21G725)
Safari Version 17.0 (17616.1.20.11.7, 17616)

![Screen Shot 2023-07-21 at 6 03 36 PM](https://github.com/chris1111/Geforce-Kepler-patcher/assets/6248794/17e48892-520f-436f-a0a2-24e3c327a5f1)

**Comment by iChris93** [comment]
Thanks. Installing the betas (Safari 17.0 and macOS 12.6.8) has things working again.
