### ISSUE TITLE
Will this project support Sonoma？

### ISSUE THREAD

**Issue by LoveJessyChen** [chris1111/Geforce-Kepler-patcher#79]

**Comment by testhmf33** [comment]
no !!!!

**Comment by LoveJessyChen** [comment]
Do you have a plan？
I want to upgrade my hackintosh to 14.0.
Current System is 11.5

**Comment by testhmf33** [comment]
i don't know , wait for a reply from CHRIS

**Comment by chris1111** [comment]
no plan to support other version

**Comment by LoveJessyChen** [comment]
When will you support macOS 14 beta?
