### ISSUE TITLE
macOS starts in recovery mode

### ISSUE THREAD

**Issue by easyax** [chris1111/Geforce-Kepler-patcher#9]
I did everything written, rebooted and now it starts in recovery mode.
(Intel Core i5-6400 2.7G 4C - NV GeForce GT730 2GB)

**Comment by chris1111** [comment]
Follow exact steps, your certainely missing some thing

**Comment by easyax** [comment]
> Follow exact steps, your certainely missing some thing

Like what? I'll check it and try again.

**Comment by bhavik66** [comment]
Same issue for me too

**Comment by chris1111** [comment]
> > Follow exact steps, your certainely missing some thing
> 
> Like what? I'll check it and try again.


Ok I should be very clear, if you follow the recommendations in relation to the 
values csr-active-config ➤ EF0F0000
If you put SecureBootModel ➤ Disabled
If you make a Clear NVRAM with the OpenCore tool, it is impossible that it will not work.

**Comment by bhavik66** [comment]
I follow all the below instructions 
Disable csrutils
Disable secure boot
Also clear NVRAM from opencore menu

But still didn't work.

**Comment by chris1111** [comment]
> I follow all the below instructions Disable csrutils Disable secure boot Also clear NVRAM from opencore menu
> 
> But still didn't work.

Impossible 
First of all did not know anything about your problem and your config, you included yourself in this subject as if nothing were

**Comment by jodkiam** [comment]
me too gt710 start with recovery

**Comment by testhmf33** [comment]
@jodkiam 
what is your hardware ?????
send by MEGA your's COMPLETE COMPRESSED EFI
